/*
 *     Generated by class-dump 3.3.3 (64 bit) (Debug version compiled Aug 11 2011 13:55:57).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#pragma mark Named Structures

struct CGPoint {
    double x;
    double y;
};

struct CGRect {
    struct CGPoint origin;
    struct CGSize size;
};

struct CGSize {
    double width;
    double height;
};

struct _NSRange {
    unsigned long long location;
    unsigned long long length;
};

#pragma mark -

/*
 * File: /Developer/Library/Xcode/PrivatePlugIns/IDELogNavigator.ideplugin/Contents/MacOS/IDELogNavigator
 * UUID: 6884D0D6-AE3C-36EB-B6ED-C7C9EE8B9691
 * Arch: Intel x86-64 (x86_64)
 *       Current version: 511.0.0, Compatibility version: 1.0.0
 *       Minimum Mac OS X version: 10.7.0
 *
 *       Objective-C Garbage Collection: Required
 *       Run path: @loader_path/../../../
 *               = /Developer/Library/Xcode/PrivatePlugIns
 */

@protocol DVTFindBarFindable

@optional
- (id)startingLocationForFindBar:(id)arg1 findingBackwards:(BOOL)arg2;
- (void)dvtFindBar:(id)arg1 didUpdateCurrentResult:(id)arg2;
- (void)dvtFindBar:(id)arg1 didUpdateResults:(id)arg2;
@end

@protocol DVTScopeBarContentController <NSObject>
@property(readonly) double preferredViewHeight;

@optional
- (void)didPressDismissOnScopeBar:(id)arg1;
@end

@protocol DVTTextFindable <NSObject>
- (id)findStringMatchingDescriptor:(id)arg1 backwards:(BOOL)arg2 from:(id)arg3 to:(id)arg4;

@optional
@property unsigned long long supportedMatchingOptions;
@end

@protocol NSObject
- (id)description;
- (unsigned long long)retainCount;
- (id)autorelease;
- (oneway void)release;
- (id)retain;
- (BOOL)respondsToSelector:(SEL)arg1;
- (BOOL)conformsToProtocol:(id)arg1;
- (BOOL)isMemberOfClass:(Class)arg1;
- (BOOL)isKindOfClass:(Class)arg1;
- (BOOL)isProxy;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2 withObject:(id)arg3;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2;
- (id)performSelector:(SEL)arg1;
- (struct _NSZone *)zone;
- (id)self;
- (Class)class;
- (Class)superclass;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
@end

@protocol XCEDataNodeAdapterP <NSObject>

@optional
- (void)dataNode:(id)arg1 forwardingCellDealloc:(id)arg2;
- (void)dataNode:(id)arg1 forwardingCell:(id)arg2 copyWithZone:(struct _NSZone *)arg3 copiedCell:(id)arg4;
- (BOOL)dataNode:(id)arg1 forwardingCell:(id)arg2 trackMouse:(id)arg3 inRect:(struct CGRect)arg4 ofView:(id)arg5 untilMouseUp:(BOOL)arg6;
- (unsigned long long)dataNode:(id)arg1 forwardingCell:(id)arg2 hitTestForEvent:(id)arg3 inRect:(struct CGRect)arg4 ofView:(id)arg5;
- (void)dataNode:(id)arg1 forwardingCell:(id)arg2 drawWithFrame:(struct CGRect)arg3 inView:(id)arg4;
- (id)dataArrayForConsistencyCheck;
- (id)dataNode:(id)arg1 toolTipForTableColumn:(id)arg2 forCell:(id)arg3 rect:(struct CGRect *)arg4 mouseLocation:(struct CGPoint)arg5;
- (id)dataNode:(id)arg1 toolTipForTableColumn:(id)arg2;
- (id)representedFilenameForDataNode:(id)arg1;
- (void)dataNodeInvalidate:(id)arg1;
- (BOOL)shouldSortChildrenOfNode:(id)arg1;
- (BOOL)isDataNodeDragDeletable:(id)arg1;
- (void)dataNode:(id)arg1 acceptDroppedItems:(id)arg2 atIndex:(long long)arg3;
- (BOOL)dataNode:(id)arg1 canAcceptDroppedItem:(id)arg2 atChildIndex:(long long)arg3;
- (BOOL)dataNode:(id)arg1 canAcceptDroppedItems:(id)arg2 atChildIndex:(long long)arg3;
- (struct CGRect)dataNode:(id)arg1 frameOfOutlineCellAtRow:(long long)arg2 defaultFrame:(struct CGRect)arg3;
- (double)heightOfRowForDataNode:(id)arg1;
- (id)inspectorViewControllersForDataNode:(id)arg1 editor:(id)arg2;
- (id)editorViewControllerForDataNode:(id)arg1;
- (BOOL)dataNode:(id)arg1 matchesPersistentObjectComponent:(id)arg2;
- (id)dataNodePersistentObjectComponent:(id)arg1;
- (long long)compareDataNode:(id)arg1 withDataNode:(id)arg2;
- (void)refreshDataNode:(id)arg1;
- (void)removeDataNode:(id)arg1;
- (BOOL)dropPaths:(id)arg1 atIndex:(long long)arg2 ofNode:(id)arg3;
- (void)renameChild:(id)arg1 withinDataNode:(id)arg2;
- (void)removeChild:(id)arg1 fromDataNode:(id)arg2;
- (id)instantiateAddedChildWithData:(id)arg1 forDataNode:(id)arg2;
- (BOOL)dataNode:(id)arg1 handleReturnKey:(id)arg2 forOutlineView:(id)arg3 changeFocus:(BOOL)arg4;
- (BOOL)dataNode:(id)arg1 handleMouseDown:(id)arg2 forOutlineView:(id)arg3 inRow:(long long)arg4 atRelativeLocation:(struct CGPoint)arg5;
- (BOOL)dataNode:(id)arg1 doubleClickInColumn:(id)arg2;
- (BOOL)filterChildData:(id)arg1 parentNode:(id)arg2 designatedAdapter:(id)arg3;
- (void)instantiateChildrenForDataNode:(id)arg1;
- (id)dataNodeImage:(id)arg1;
- (BOOL)isDataNodeSelectable:(id)arg1;
- (BOOL)isDataNodeExpandedByDefault:(id)arg1;
- (BOOL)isDataNodeExpandable:(id)arg1;
- (BOOL)dataNode:(id)arg1 outlineViewIsGroupItem:(id)arg2;
- (BOOL)dataNode:(id)arg1 outlineViewShouldShowOutlineCell:(id)arg2;
- (id)dataNode:(id)arg1 outlineView:(id)arg2 dataCellForTableColumn:(id)arg3;
- (void)dataNode:(id)arg1 outlineView:(id)arg2 willDisplayCell:(id)arg3 forTableColumn:(id)arg4;
- (BOOL)dataNode:(id)arg1 shouldEditTableColumn:(id)arg2;
- (void)dataNode:(id)arg1 setObjectValue:(id)arg2 forTableColumn:(id)arg3;
- (id)dataNode:(id)arg1 objectValueForTableColumn:(id)arg2;
- (void)dataNodeConfigure:(id)arg1;
@end

@interface IDELogInProgressTransformer : NSValueTransformer
{
}

+ (BOOL)allowsReverseTransformation;
+ (Class)transformedValueClass;
- (id)transformedValue:(id)arg1;

@end

@interface IDELogNavigator : IDENavigator
{
    NSTableColumn *_mainTableColumn;
    DVTScopeBarView *_scopeBarView;
    NSPredicate *_groupingPredicate;
    NSArray *_selectedObjects;
    IDENavigatorDataCell *_logHeaderCell;
    IDENavigatorDataCell *_activityLogCell;
    IDENavigatorDataCell *_substructureCell;
    NSArray *_expandedItems;
    NSArray *_expandedItemsBeforeFiltering;
    IDENavigatorOutlineView *_outlineView;
    NSString *_filterPatternString;
    NSMutableArray *_stateChangeObservingTokens;
    BOOL _restoringState;
    BOOL _keepSelectionWhenRestoringState;
    BOOL _recentsOnlyFilteringEnabled;
}

+ (id)imageForTypeIdentifier:(id)arg1;
+ (void)configureStateSavingObjectPersistenceByName:(id)arg1;
+ (id)appHeaderImage;
+ (id)clockImage;
+ (id)imageNamed:(id)arg1;
+ (void)initialize;
@property(copy) NSPredicate *groupingPredicate; // @synthesize groupingPredicate=_groupingPredicate;
@property BOOL recentsOnlyFilteringEnabled; // @synthesize recentsOnlyFilteringEnabled=_recentsOnlyFilteringEnabled;
@property(copy) NSString *filterPatternString; // @synthesize filterPatternString=_filterPatternString;
@property IDENavigatorOutlineView *outlineView; // @synthesize outlineView=_outlineView;
@property(retain) NSArray *selectedObjects; // @synthesize selectedObjects=_selectedObjects;
- (double)outlineView:(id)arg1 heightOfRowByItem:(id)arg2;
- (id)outlineView:(id)arg1 dataCellForTableColumn:(id)arg2 item:(id)arg3;
- (BOOL)outlineView:(id)arg1 shouldSelectItem:(id)arg2;
- (BOOL)outlineView:(id)arg1 isGroupHeaderItem:(id)arg2;
- (id)cellForItem:(id)arg1;
- (id)substructureCell;
- (id)activityLogCell;
- (id)logHeaderCell;
- (void)setOutputSelection:(id)arg1;
- (void)updateBoundSelection;
@property(copy) NSString *visibleRectString;
@property(copy) NSArray *stateSavingSelectedObjects;
- (void)revealNavigableItems:(id)arg1;
@property(copy) NSArray *stateSavingExpandedItems;
- (void)commitStateToDictionary:(id)arg1;
- (void)revertStateWithDictionary:(id)arg1;
- (void)_configureStateSavingObservers;
- (id)filterDefinitionIdentifier;
- (void)_clearFilterPredicate;
- (void)updateFilterPredicate;
- (id)_recentLogRecords;
- (BOOL)_isFiltered;
- (id)nameArraysForItems:(id)arg1;
- (id)navigableItemWithName:(id)arg1 inArray:(id)arg2;
- (void)setFilteringEnabled:(BOOL)arg1;
- (void)setFilterPredicate:(id)arg1;
- (void)_synchronizeFilteringWithOutlineView;
- (void)expandTopLevels;
- (BOOL)delegateFirstResponder;
- (void)invalidate;
- (void)loadView;
- (id)dvtExtraBindings;
- (void)openDoubleClickedNavigableItemsAction:(id)arg1;
- (void)openClickedNavigableItemAction:(id)arg1;
- (void)openSelectedNavigableItemsKeyAction:(id)arg1;
- (id)openSpecifierForNavigableItem:(id)arg1 error:(id *)arg2;
- (id)domainIdentifier;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(copy) NSArray *expandedItems; // @dynamic expandedItems;
@property(readonly) NSMutableArray *mutableExpandedItems; // @dynamic mutableExpandedItems;

@end

@interface IDENavigableItemWorkspaceLogsDomainProvider : IDENavigableItemDomainProvider
{
}

+ (id)domainObjectForWorkspace:(id)arg1;

@end

@interface IDELogEditor : IDEEditor <DVTFindBarFindable>
{
    XCBuildResultsOutlineView *_buildResultsOutlineView;
    XCBuildResultsOutlineView *_buildIssuesOutlineView;
    NSBox *_activeViewHolder;
    IDEBuildResultsOutlineLogic *_outlineLogic;
    NSPopUpButton *_scopeBarMessagesPopup;
    NSArray *_currentSelectedDocumentLocations;
    NSArray *_currentSelectedItems;
    NSIndexPath *_lastFindResultIndexPath;
    struct _NSRange _lastFindResultRange;
    IDEActivityLogSection *_lastFindResultSection;
    IDELogEditorScopeBar *_logEditorScopeBar;
    BOOL _showBySteps;
    BOOL _showAllResults;
    BOOL _lastFindResult;
}

+ (long long)version;
+ (void)configureStateSavingObjectPersistenceByName:(id)arg1;
@property(readonly) IDEActivityLogSection *lastFindResultSection; // @synthesize lastFindResultSection=_lastFindResultSection;
@property(readonly) struct _NSRange lastFindResultRange; // @synthesize lastFindResultRange=_lastFindResultRange;
@property(readonly) BOOL lastFindResult; // @synthesize lastFindResult=_lastFindResult;
@property(copy) NSArray *currentSelectedItems; // @synthesize currentSelectedItems=_currentSelectedItems;
@property(copy) NSArray *currentSelectedDocumentLocations; // @synthesize currentSelectedDocumentLocations=_currentSelectedDocumentLocations;
- (void)commitStateToDictionary:(id)arg1;
- (void)revertStateWithDictionary:(id)arg1;
- (void)invalidate;
- (void)menuCmd_showErrorsOnly:(id)arg1;
- (void)menuCmd_showAllIssues:(id)arg1;
- (void)menuCmd_showAllMessages:(id)arg1;
- (void)menuCmd_showRecentResults:(id)arg1;
- (void)menuCmd_showAllResults:(id)arg1;
- (void)menuCmd_copyShownTranscripts:(id)arg1;
- (void)menuCmd_copySelectedTranscripts:(id)arg1;
- (void)menuCmd_collapseAllTranscripts:(id)arg1;
- (void)menuCmd_expandAllTranscripts:(id)arg1;
- (void)menuCmd_collapseSelectedTranscripts:(id)arg1;
- (void)menuCmd_expandSelectedTranscripts:(id)arg1;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (id)startingLocationForFindBar:(id)arg1 findingBackwards:(BOOL)arg2;
- (void)dvtFindBar:(id)arg1 didUpdateCurrentResult:(id)arg2;
- (void)dvtFindBar:(id)arg1 didUpdateResults:(id)arg2;
- (void)doubleClickDocumentLocation:(id)arg1;
- (void)showFindIndicatorInTranscriptForDocumentLocation:(id)arg1;
- (void)selectDocumentLocations:(id)arg1;
- (void)processNewSelectedIndexPaths:(id)arg1;
- (void)takeFocus;
- (void)viewDidInstall;
- (void)loadView;
- (void)logEditorScopeBar:(id)arg1 searchTextChanged:(id)arg2;
- (void)logEditorScopeBar:(id)arg1 showAllResultsChanged:(BOOL)arg2;
- (void)_setShowAllResults:(BOOL)arg1;
- (void)logEditorScopeBar:(id)arg1 stateChanged:(int)arg2;
- (id)attributesForScopeBarMenuItems;
- (void)showAllMessages:(id)arg1;
- (void)_showAnalyzerResultsForSelectability;
- (void)_showWarningsForSelectability;
- (void)_showErrorsForSelectability;
- (void)scopeBarMenuStaticAnalysisResultsOnly:(id)arg1;
- (void)scopeBarMenuErrorsOnly:(id)arg1;
- (void)scopeBarMenuErrorsAndWarningsOnly:(id)arg1;
- (void)scopeBarMenuAllIssues:(id)arg1;
- (void)scopeBarMenuAllMessages:(id)arg1;
- (void)_updateShowSteps:(BOOL)arg1 showWarnings:(BOOL)arg2 showErrors:(BOOL)arg3 showAnalyzerResults:(BOOL)arg4;
- (void)_setShowSteps:(BOOL)arg1 showWarnings:(BOOL)arg2 showErrors:(BOOL)arg3 showAnalyzerResults:(BOOL)arg4;
- (void)showLatestResults:(id)arg1;
- (void)showAllResults:(id)arg1;
- (void)_updateShownView;
- (void)_updateScopeBar;
- (id)activeView;
- (id)localizedString:(id)arg1 explanation:(id)arg2;
- (void)configureOutlineView:(id)arg1;

@end

@interface XCEForwardingCell : NSCell
{
    IDEConfigurableDataNode *_dataNode;
}

@property(nonatomic) IDEConfigurableDataNode *dataNode; // @synthesize dataNode=_dataNode;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (BOOL)trackMouse:(id)arg1 inRect:(struct CGRect)arg2 ofView:(id)arg3 untilMouseUp:(BOOL)arg4;
- (unsigned long long)hitTestForEvent:(id)arg1 inRect:(struct CGRect)arg2 ofView:(id)arg3;
- (void)drawWithFrame:(struct CGRect)arg1 inView:(id)arg2;

@end

@interface XCBuildResultsCell : XCEForwardingCell
{
    NSButtonCell *_expandButtonCell;
}

- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (BOOL)accessibilityIsAttributeSettable:(id)arg1;
- (id)accessibilityAttributeValue:(id)arg1;
- (id)accessibilityAttributeNames;
- (BOOL)accessibilityIsIgnored;
- (void)expandAction:(id)arg1;
@property(readonly, nonatomic) NSButtonCell *expandButtonCell; // @dynamic expandButtonCell;

@end

@interface XCBuildResultsOutlineView : NSOutlineView
{
    long long _mouseRow;
    BOOL _withinDrawRect;
    double _xceLastWidth;
    BOOL _changedWidthWhileLiveResizing;
    XCTranscriptTextView *_textView;
    NSArray *_collapsedItems;
    NSArray *_expandedItems;
    NSArray *_selectedItems;
    NSArray *_itemsWithExpandedTranscripts;
    struct CGPoint _scrollPositionAllResults;
    BOOL _scrollerIsPinnedToBottomAllResults;
    struct CGPoint _scrollPositionLatestResults;
    BOOL _scrollerIsPinnedToBottomLatestResults;
    BOOL _batchUpdateMode;
    BOOL _cleared;
}

@property(nonatomic) BOOL scrollerIsPinnedToBottomLatestResults; // @synthesize scrollerIsPinnedToBottomLatestResults=_scrollerIsPinnedToBottomLatestResults;
@property(nonatomic) struct CGPoint scrollPositionLatestResults; // @synthesize scrollPositionLatestResults=_scrollPositionLatestResults;
@property(nonatomic) BOOL scrollerIsPinnedToBottomAllResults; // @synthesize scrollerIsPinnedToBottomAllResults=_scrollerIsPinnedToBottomAllResults;
@property(nonatomic) struct CGPoint scrollPositionAllResults; // @synthesize scrollPositionAllResults=_scrollPositionAllResults;
@property(retain) NSArray *itemsWithExpandedTranscripts; // @synthesize itemsWithExpandedTranscripts=_itemsWithExpandedTranscripts;
@property(retain) NSArray *selectedItems; // @synthesize selectedItems=_selectedItems;
@property(retain) NSArray *expandedItems; // @synthesize expandedItems=_expandedItems;
@property(retain) NSArray *collapsedItems; // @synthesize collapsedItems=_collapsedItems;
@property(nonatomic) XCTranscriptTextView *textView; // @synthesize textView=_textView;
@property(nonatomic) long long mouseRow; // @synthesize mouseRow=_mouseRow;
- (void)dealloc;
- (void)clearOutlineView;
- (BOOL)becomeFirstResponder;
- (void)scrollToEnd;
- (BOOL)shouldScrollToEnd;
- (void)mouseDown:(id)arg1;
- (id)menuForEvent:(id)arg1;
- (void)selectPreviousContentSibling:(id)arg1;
- (void)selectNextContentSibling:(id)arg1;
- (void)selectContentChild:(id)arg1;
- (void)selectContentParent:(id)arg1;
- (void)jumpToSelection:(id)arg1;
- (void)copy:(id)arg1;
- (id)selectedNodes;
- (id)selectedData;
@property(readonly, nonatomic) IDEConfigurableDataSource *xceDataSource; // @dynamic xceDataSource;
- (void)_widthChanged:(id)arg1;
- (void)viewDidEndLiveResize;
- (void)viewWillStartLiveResize;
- (void)viewWillDraw;
- (void)_checkForChangedWidth;
- (void)_updateAllRowHeights;
- (void)setNeedsDisplayInRect:(struct CGRect)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)updateTrackingAreas;
- (void)clearTextView;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)cursorUpdate:(id)arg1;
- (void)mouseMoved:(id)arg1;
- (void)_reflectMouseRow:(id)arg1;
- (void)_updateForOldMouseRow;
- (void)keyDown:(id)arg1;
- (struct CGRect)frameOfOutlineCellAtRow:(long long)arg1;
- (void)_redisplayAfterExpansionChangeFromRow:(long long)arg1 withOriginalRowCount:(long long)arg2;
- (void)xceSetBatchUpdateMode:(BOOL)arg1;
- (double)xceLastWidth;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)_initCommon;

@end

@interface XCLogItemCounts : NSObject
{
    unsigned long long _errors;
    unsigned long long _warnings;
    unsigned long long _analyzerResults;
    unsigned long long _analyzerWarnings;
}

@property(nonatomic) unsigned long long analyzerWarnings; // @synthesize analyzerWarnings=_analyzerWarnings;
@property(nonatomic) unsigned long long analyzerResults; // @synthesize analyzerResults=_analyzerResults;
@property(nonatomic) unsigned long long warnings; // @synthesize warnings=_warnings;
@property(nonatomic) unsigned long long errors; // @synthesize errors=_errors;

@end

@interface XCBuildResultAdapter : NSObject <XCEDataNodeAdapterP>
{
    XCBuildResultsCell *_forwardingCell;
}

- (id)accessibilityDescriptionForDataNode:(id)arg1;
- (id)dataNode:(id)arg1 outlineView:(id)arg2 dataCellForTableColumn:(id)arg3;
- (BOOL)isKeyAndFirstResponderForOutlineView:(id)arg1;
- (id)createTextViewForDataNode:(id)arg1;
- (void)expandActionForDataNode:(id)arg1;
- (void)_scrollToEndForDataNode:(id)arg1;
- (void)_recursiveSetTextExpanded:(BOOL)arg1 inDataNode:(id)arg2;
- (BOOL)textExpandedForDataNode:(id)arg1;
- (void)setTextExpanded:(BOOL)arg1 forDataNode:(id)arg2;
- (BOOL)expandableTitleForDataNode:(id)arg1;
- (BOOL)supportsTextExpansionAtMessageLevelForDataNode:(id)arg1;
- (BOOL)supportsTextExpansionAtSectionLevelForDataNode:(id)arg1;
- (BOOL)supportsTextExpansionForDataNode:(id)arg1;
- (BOOL)dataNode:(id)arg1 doubleClickInColumn:(id)arg2;
- (id)newAttributesForFont:(id)arg1 color:(id)arg2;
- (id)textColorForDataNode:(id)arg1;
- (double)verticaImageOffsetForDataNode:(id)arg1;
- (double)titleFontHeigthForDataNode:(id)arg1;
- (id)titleFontForDataNode:(id)arg1;
- (id)defaultBoldFont;
- (double)defaultFontHeight;
- (id)defaultFont;
- (id)imageForDataNode:(id)arg1;
- (id)titleForDataNode:(id)arg1;

@end

@interface XCLogItemAdapter : XCBuildResultAdapter
{
}

- (id)dataNodePersistentObjectComponent:(id)arg1;
- (void)dataNode:(id)arg1 forwardingCellDealloc:(id)arg2;
- (void)dataNode:(id)arg1 forwardingCell:(id)arg2 copyWithZone:(struct _NSZone *)arg3 copiedCell:(id)arg4;
- (BOOL)dataNode:(id)arg1 forwardingCell:(id)arg2 trackMouse:(id)arg3 inRect:(struct CGRect)arg4 ofView:(id)arg5 untilMouseUp:(BOOL)arg6;
- (unsigned long long)dataNode:(id)arg1 forwardingCell:(id)arg2 hitTestForEvent:(id)arg3 inRect:(struct CGRect)arg4 ofView:(id)arg5;
- (void)dataNode:(id)arg1 forwardingCell:(id)arg2 drawWithFrame:(struct CGRect)arg3 inView:(id)arg4;
- (struct CGRect)optionalTextFrameForCellFrame:(struct CGRect)arg1 inOutlineView:(id)arg2 forDataNode:(id)arg3;
- (id)accessibilityDescriptionForDataNode:(id)arg1;
- (id)secondRowStringForDataNode:(id)arg1;
- (id)titleSecondPartForDataNode:(id)arg1;
- (id)targetHeadingBadgeForDataNode:(id)arg1;
- (struct CGRect)_drawSummaryBackgroundInFrame:(struct CGRect)arg1 forDataNode:(id)arg2;
- (struct CGRect)_drawSummaryBackgroundWithRoundedRectInFrame:(struct CGRect)arg1 forDataNode:(id)arg2;
- (void)_drawExpandedTitleInFrame:(struct CGRect)arg1 selected:(BOOL)arg2 forDataNode:(id)arg3;
- (void)_drawOptionalTextInFrame:(struct CGRect)arg1 inView:(id)arg2 forDataNode:(id)arg3;
- (struct CGRect)drawAllIssuesForDataNode:(id)arg1 inFrame:(struct CGRect)arg2 attributes:(id)arg3 doDraw:(BOOL)arg4;
- (struct CGRect)drawIssues:(unsigned long long)arg1 withImage:(id)arg2 inFrame:(struct CGRect)arg3 attributes:(id)arg4 doDraw:(BOOL)arg5 verticalImageOffset:(double)arg6;
- (void)_updateButtonImagesForButtonCell:(id)arg1 inFrame:(struct CGRect)arg2 selectionKnown:(BOOL)arg3 selected:(BOOL)arg4 forDataNode:(id)arg5;
- (struct CGRect)_expandButtonFrameForFrame:(struct CGRect)arg1 ofView:(id)arg2 knownToDisplay:(BOOL)arg3 forDataNode:(id)arg4;
- (BOOL)shouldDrawButtonForExpandingTitleForDataNode:(id)arg1;
- (BOOL)shouldDrawButtonForExpandingTitle:(id)arg1 attributes:(id)arg2 forDataNode:(id)arg3;
- (BOOL)drawInMouseRowForDataNode:(id)arg1;
- (BOOL)anyImportantMessagesForDataNode:(id)arg1;
- (BOOL)anyIssuesForDataNode:(id)arg1;
- (unsigned long long)analyzerResultsForDataNode:(id)arg1;
- (unsigned long long)analyzerWarningsForDataNode:(id)arg1;
- (unsigned long long)warningsForDataNode:(id)arg1;
- (unsigned long long)errorsForDataNode:(id)arg1;
- (void)_drawRoundedRect:(struct CGRect)arg1 bgColor:(id)arg2 fgColor:(id)arg3;
- (void)_drawOvalInRect:(struct CGRect)arg1 bgColor:(id)arg2 fgColor:(id)arg3;
- (BOOL)isSummaryAdapter;
- (BOOL)isTargetHeadingAdapter;
- (BOOL)isInvocationAdapter;
- (BOOL)isUnitTestAdapter;
- (BOOL)filterChildData:(id)arg1 parentNode:(id)arg2 designatedAdapter:(id)arg3;
- (id)instantiateAddedChildWithData:(id)arg1 forDataNode:(id)arg2;
- (void)instantiateChildrenForDataNode:(id)arg1;
- (BOOL)dataNode:(id)arg1 handleReturnKey:(id)arg2 forOutlineView:(id)arg3 changeFocus:(BOOL)arg4;
- (id)subitemsForDataNode:(id)arg1;
- (BOOL)dataNode:(id)arg1 shouldEditTableColumn:(id)arg2;
- (BOOL)hasTranscriptForDataNode:(id)arg1;
- (BOOL)isDataNodeSelectable:(id)arg1;
- (BOOL)isDataNodeExpandable:(id)arg1;
- (void)dataNode:(id)arg1 outlineView:(id)arg2 willDisplayCell:(id)arg3 forTableColumn:(id)arg4;
- (double)heightOfRowForDataNode:(id)arg1;
- (double)_baseHeightOfRowForDataNode:(id)arg1;
- (id)dataNode:(id)arg1 objectValueForTableColumn:(id)arg2;
- (void)dataNodeConfigure:(id)arg1;
- (void)dealloc;
- (id)init;

@end

@interface IDEActivityLogTranscriptLayoutManager : NSLayoutManager
{
}

- (struct _NSRange)glyphRangeForBoundingRect:(struct CGRect)arg1 inTextContainer:(id)arg2;
- (void)setExtraLineFragmentRect:(struct CGRect)arg1 usedRect:(struct CGRect)arg2 textContainer:(id)arg3;

@end

@interface XCETextLayoutTextStorage : NSTextStorage
{
    NSMutableAttributedString *_contents;
}

- (struct _NSRange)findString:(id)arg1 previousFindRange:(struct _NSRange)arg2 limitRange:(struct _NSRange)arg3 options:(unsigned long long)arg4 matchStyle:(long long)arg5 wrap:(BOOL)arg6;
- (id)attributesAtIndex:(unsigned long long)arg1 effectiveRange:(struct _NSRange *)arg2;
- (id)string;
- (void)setAttributes:(id)arg1 range:(struct _NSRange)arg2;
- (void)replaceCharactersInRange:(struct _NSRange)arg1 withString:(id)arg2;
- (void)replaceCharactersInRange:(struct _NSRange)arg1 withAttributedString:(id)arg2;
- (void)dealloc;
- (id)init;

@end

@interface XCEColoredRect : NSObject
{
    struct _NSRange _range;
    struct CGRect _rect;
    NSColor *_color;
    id _reference;
}

@property(retain, nonatomic) id reference; // @synthesize reference=_reference;
@property(retain, nonatomic) NSColor *color; // @synthesize color=_color;
@property(nonatomic) struct CGRect rect; // @synthesize rect=_rect;
@property(nonatomic) struct _NSRange range; // @synthesize range=_range;

@end

@interface XCETextLayout : NSObject
{
    NSLayoutManager *_layoutManager;
    struct _NSRange _glyphRange;
    double _usedHeight;
    BOOL _layoutDone;
    NSArray *_coloredRects;
}

@property(retain, nonatomic) NSArray *coloredRects; // @synthesize coloredRects=_coloredRects;
@property(nonatomic) struct _NSRange glyphRange; // @synthesize glyphRange=_glyphRange;
@property(readonly, nonatomic) NSLayoutManager *layoutManager; // @synthesize layoutManager=_layoutManager;
- (void)addColoredRectsForRange:(struct _NSRange)arg1 color:(id)arg2 reference:(id)arg3 toArray:(id)arg4;
- (void)drawColoredRects:(id)arg1 forTextOrigin:(struct CGPoint)arg2;
- (double)heightAtCharacterPosition:(unsigned long long)arg1;
- (void)drawAt:(struct CGPoint)arg1;
@property(readonly, nonatomic) double usedHeight;
@property(nonatomic) double width; // @dynamic width;
- (void)_doLayout;
- (void)setAttributedString:(id)arg1;
- (void)invalidateLayout;
@property(readonly, nonatomic) NSTextContainer *textContainer;
@property(readonly, nonatomic) NSTextStorage *textStorage;
- (void)dealloc;
- (id)init;

@end

@interface XCBuildResultsTextLayout : XCETextLayout
{
    unsigned long long _commandDetailLength;
    double _commandDetailHeight;
    unsigned long long _totalLengthUsed;
}

- (id)coloredRectsForSection:(id)arg1;
@property(readonly, nonatomic) double commandDetailHeight;
- (void)_doLayout;
- (void)resetForLogMessage:(id)arg1 forDataNode:(id)arg2;
- (id)newMessageAttributesForFont:(id)arg1 color:(id)arg2;
- (void)resetForLogSection:(id)arg1 forDataNode:(id)arg2;

@end

@interface XCTranscriptTextView : NSTextView
{
    XCBuildResultsTextLayout *_textLayout;
    IDEConfigurableDataNode *_dataNode;
    struct CGRect _cellFrame;
}

@property(nonatomic) struct CGRect cellFrame; // @synthesize cellFrame=_cellFrame;
@property(nonatomic) IDEConfigurableDataNode *dataNode; // @synthesize dataNode=_dataNode;
@property(nonatomic) XCBuildResultsTextLayout *textLayout; // @synthesize textLayout=_textLayout;
- (void)dealloc;
- (void)enterSelection:(id)arg1;
- (void)useSelectionForReplace:(id)arg1;
- (void)useSelectionForFind:(id)arg1;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (void)mouseDown:(id)arg1;
- (BOOL)singleTranscriptFindText:(id)arg1 ignoreCase:(BOOL)arg2 matchStyle:(long long)arg3 backwards:(BOOL)arg4 wrap:(BOOL)arg5;
- (BOOL)findText:(id)arg1 ignoreCase:(BOOL)arg2 matchStyle:(long long)arg3 backwards:(BOOL)arg4 wrap:(BOOL)arg5;

@end

@interface XCLogSectionAdapter : XCLogItemAdapter
{
}

- (struct CGRect)dataNode:(id)arg1 frameOfOutlineCellAtRow:(long long)arg2 defaultFrame:(struct CGRect)arg3;
- (BOOL)dataNode:(id)arg1 handleMouseDown:(id)arg2 forOutlineView:(id)arg3 inRow:(long long)arg4 atRelativeLocation:(struct CGPoint)arg5;
- (id)createTextViewForDataNode:(id)arg1;
- (void)_drawOptionalTextInFrame:(struct CGRect)arg1 inView:(id)arg2 forDataNode:(id)arg3;
- (double)heightOfRowForDataNode:(id)arg1;
- (double)_baseHeightOfRowForDataNode:(id)arg1;
- (id)dataNode:(id)arg1 toolTipForTableColumn:(id)arg2;
- (id)subitemsForDataNode:(id)arg1;
- (unsigned long long)analyzerResultsForDataNode:(id)arg1;
- (unsigned long long)analyzerWarningsForDataNode:(id)arg1;
- (unsigned long long)warningsForDataNode:(id)arg1;
- (unsigned long long)errorsForDataNode:(id)arg1;
- (id)imageForDataNode:(id)arg1;
- (id)titleForDataNode:(id)arg1;

@end

@interface XCLogTargetHeadingAdapter : XCLogSectionAdapter
{
}

- (BOOL)dataNode:(id)arg1 doubleClickInColumn:(id)arg2;
- (id)targetHeadingBadgeForDataNode:(id)arg1;
- (id)secondRowStringForDataNode:(id)arg1;
- (id)titleFontForDataNode:(id)arg1;
- (id)titleForDataNode:(id)arg1;
- (id)imageForDataNode:(id)arg1;
- (double)_baseHeightOfRowForDataNode:(id)arg1;
- (BOOL)supportsTextExpansionAtSectionLevelForDataNode:(id)arg1;
- (BOOL)supportsTextExpansionForDataNode:(id)arg1;
- (BOOL)isTargetHeadingAdapter;

@end

@interface XCLogInvocationAdapter : XCLogSectionAdapter
{
}

- (id)dataNodePersistentObjectComponent:(id)arg1;
- (id)titleSecondPartForDataNode:(id)arg1;
- (id)titleForDataNode:(id)arg1;
- (id)dataNode:(id)arg1 toolTipForTableColumn:(id)arg2;
- (BOOL)supportsTextExpansionAtSectionLevelForDataNode:(id)arg1;
- (BOOL)supportsTextExpansionForDataNode:(id)arg1;
- (BOOL)isInvocationAdapter;

@end

@interface XCLogMessageAdapter : XCLogItemAdapter
{
}

- (struct CGRect)dataNode:(id)arg1 frameOfOutlineCellAtRow:(long long)arg2 defaultFrame:(struct CGRect)arg3;
- (void)_drawExpandedTitleInFrame:(struct CGRect)arg1 selected:(BOOL)arg2 forDataNode:(id)arg3;
- (double)heightOfRowForDataNode:(id)arg1;
- (BOOL)dataNode:(id)arg1 handleMouseDown:(id)arg2 forOutlineView:(id)arg3 inRow:(long long)arg4 atRelativeLocation:(struct CGPoint)arg5;
- (void)highlightMessageForNode:(id)arg1;
- (id)dataNodePersistentObjectComponent:(id)arg1;
- (id)dataNode:(id)arg1 toolTipForTableColumn:(id)arg2;
- (id)subitemsForDataNode:(id)arg1;
- (id)textColorForDataNode:(id)arg1;
- (BOOL)supportsTextExpansionAtMessageLevelForDataNode:(id)arg1;
- (BOOL)supportsTextExpansionForDataNode:(id)arg1;
- (BOOL)expandableTitleForDataNode:(id)arg1;
- (id)titleForDataNode:(id)arg1;

@end

@interface XCLogNoticeAdapter : XCLogMessageAdapter
{
}

@end

@interface XCLogErrorAdapter : XCLogMessageAdapter
{
}

- (unsigned long long)errorsForDataNode:(id)arg1;
- (id)imageForDataNode:(id)arg1;
- (id)textColorForDataNode:(id)arg1;

@end

@interface XCLogWarningAdapter : XCLogMessageAdapter
{
}

- (unsigned long long)warningsForDataNode:(id)arg1;
- (id)imageForDataNode:(id)arg1;

@end

@interface XCLogAnalyzerWarningAdapter : XCLogMessageAdapter
{
}

- (unsigned long long)analyzerWarningsForDataNode:(id)arg1;
- (id)imageForDataNode:(id)arg1;

@end

@interface XCLogAnalyzerResultAdapter : XCLogMessageAdapter
{
}

- (unsigned long long)analyzerResultsForDataNode:(id)arg1;
- (id)imageForDataNode:(id)arg1;

@end

@interface XCLogAnalyzerStepAdapter : XCLogMessageAdapter
{
}

- (id)titleForDataNode:(id)arg1;
- (id)imageForDataNode:(id)arg1;

@end

@interface XCLogAnalyzerEventStepAdapter : XCLogAnalyzerStepAdapter
{
}

- (id)imageForDataNode:(id)arg1;

@end

@interface XCLogAnalyzerControlFlowStepAdapter : XCLogAnalyzerStepAdapter
{
}

- (id)imageForDataNode:(id)arg1;

@end

@interface XCLogUnitTestAdapter : XCLogSectionAdapter
{
}

- (BOOL)anyImportantMessagesForDataNode:(id)arg1;
- (unsigned long long)analyzerResultsForDataNode:(id)arg1;
- (unsigned long long)analyzerWarningsForDataNode:(id)arg1;
- (unsigned long long)warningsForDataNode:(id)arg1;
- (unsigned long long)errorsForDataNode:(id)arg1;
- (id)dataNode:(id)arg1 toolTipForTableColumn:(id)arg2;
- (id)titleSecondPartForDataNode:(id)arg1;
- (BOOL)supportsTextExpansionAtSectionLevelForDataNode:(id)arg1;
- (BOOL)supportsTextExpansionForDataNode:(id)arg1;
- (BOOL)isUnitTestAdapter;

@end

@interface XCLogHeaderInclusionAdapter : XCLogMessageAdapter
{
}

@end

@interface XCLogSummaryItemAdapter : XCLogItemAdapter
{
}

- (id)secondRowStringForDataNode:(id)arg1;
- (id)titleFontForDataNode:(id)arg1;
- (id)titleForDataNode:(id)arg1;
- (id)imageForDataNode:(id)arg1;
- (id)imageNamed:(id)arg1;
- (unsigned long long)analyzerWarningsForDataNode:(id)arg1;
- (unsigned long long)analyzerResultsForDataNode:(id)arg1;
- (unsigned long long)warningsForDataNode:(id)arg1;
- (unsigned long long)errorsForDataNode:(id)arg1;
- (BOOL)isSummaryAdapter;
- (BOOL)isDataNodeSelectable:(id)arg1;
- (double)heightOfRowForDataNode:(id)arg1;

@end

@interface XCBuildIssueBaseClassAdapter : XCBuildResultAdapter
{
}

- (BOOL)dataNode:(id)arg1 handleReturnKey:(id)arg2 forOutlineView:(id)arg3 changeFocus:(BOOL)arg4;
- (void)dataNode:(id)arg1 forwardingCell:(id)arg2 drawWithFrame:(struct CGRect)arg3 inView:(id)arg4;
- (id)newAttributesForFont:(id)arg1 color:(id)arg2;
- (id)backgroundColor;
- (double)heightOfRowForDataNode:(id)arg1;
- (void)dataNode:(id)arg1 outlineView:(id)arg2 willDisplayCell:(id)arg3 forTableColumn:(id)arg4;
- (id)dataNode:(id)arg1 objectValueForTableColumn:(id)arg2;
- (BOOL)dataNode:(id)arg1 shouldEditTableColumn:(id)arg2;
- (BOOL)isDataNodeSelectable:(id)arg1;
- (BOOL)isDataNodeExpandable:(id)arg1;
- (void)dealloc;
- (id)init;

@end

@interface XCBuildIssueCategoryAdapter : XCBuildIssueBaseClassAdapter
{
}

- (id)dataNodePersistentObjectComponent:(id)arg1;
- (id)backgroundColor;
- (id)imageForDataNode:(id)arg1;
- (id)titleForDataNode:(id)arg1;

@end

@interface XCBuildIssueOccurrenceAdapter : XCBuildIssueBaseClassAdapter
{
}

- (void)instantiateChildrenForDataNode:(id)arg1;
- (BOOL)isDataNodeExpandable:(id)arg1;
- (id)dataNodePersistentObjectComponent:(id)arg1;
- (id)dataNode:(id)arg1 toolTipForTableColumn:(id)arg2;
- (id)imageForDataNode:(id)arg1;
- (id)titleForDataNode:(id)arg1;

@end

@interface XCBuildIssueOccurrenceSubStepAdapter : XCBuildIssueBaseClassAdapter
{
}

- (id)dataNodePersistentObjectComponent:(id)arg1;
- (id)dataNode:(id)arg1 toolTipForTableColumn:(id)arg2;
- (id)imageForDataNode:(id)arg1;
- (id)titleForDataNode:(id)arg1;

@end

@interface IDEBuildResultsOutlineLogic : NSObject
{
    IDELogEditor *_editor;
    IDEActivityLog *_activityLog;
    IDEActivityLogRecorder *_observedRecorder;
    XCBuildResultsOutlineView *_outline;
    XCBuildResultsOutlineView *_outlineIssues;
    XCBuildResultsOutlineView *_activeOutline;
    IDEConfigurableDataSource *_dataSource;
    IDEConfigurableDataSource *_dataSourceIssues;
    BOOL _showSteps;
    BOOL _showWarnings;
    BOOL _showErrors;
    BOOL _showAnalyzerResults;
    BOOL _showAllResults;
    BOOL _startNotificationWasReceived;
    BOOL _stopNotificationWasReceived;
    BOOL _expandingWhileBuilding;
    BOOL _performScrollToEnd;
    XCBuildResultAdapter *_genericLogItemAdapter;
    XCBuildResultAdapter *_sectionAdapter;
    XCBuildResultAdapter *_targetHeadingAdapter;
    XCBuildResultAdapter *_invocationAdapter;
    XCBuildResultAdapter *_errorAdapter;
    XCBuildResultAdapter *_warningAdapter;
    XCBuildResultAdapter *_analyzerWarningAdapter;
    XCBuildResultAdapter *_analyzerResultAdapter;
    XCBuildResultAdapter *_analyzerStepAdapter;
    XCBuildResultAdapter *_analyzerControlFlowStepAdapter;
    XCBuildResultAdapter *_analyzerEventStepAdapter;
    XCBuildResultAdapter *_unitTestAdapter;
    XCBuildResultAdapter *_headerInclusionAdapter;
    XCBuildResultAdapter *_noticeAdapter;
    XCBuildResultAdapter *_summaryItemAdapter;
    XCBuildResultAdapter *_issueCategoryAdapter;
    XCBuildResultAdapter *_issueOccurrenceAdapter;
    XCBuildResultAdapter *_issueOccurrenceSubStepAdapter;
    NSMapTable *_textLayoutsGenerationA;
    NSMapTable *_textLayoutsGenerationB;
    NSMutableDictionary *_issueCategoryNodes;
    NSString *_searchFieldValue;
}

+ (id)markerForOtherCategory;
+ (BOOL)isUnitTestSection:(id)arg1;
+ (BOOL)isContextInfoMessage:(id)arg1;
+ (BOOL)isHeaderInclusionMessage:(id)arg1;
+ (BOOL)isAnalyzerWarningMessage:(id)arg1;
+ (BOOL)isAnalyzerEventStepMessage:(id)arg1;
+ (BOOL)isAnalyzerControlFlowStepMessage:(id)arg1;
+ (BOOL)isAnalyzerStepMessage:(id)arg1;
+ (BOOL)isAnalyzerResultMessage:(id)arg1;
+ (BOOL)isNoticeMessage:(id)arg1;
+ (BOOL)isWarningMessage:(id)arg1;
+ (BOOL)isErrorMessage:(id)arg1;
+ (BOOL)isCommandInvocationSection:(id)arg1;
+ (BOOL)isMainGroupSection:(id)arg1;
+ (id)formattedLogTranscript:(id)arg1;
+ (id)formattedLogStringForLogMessage:(id)arg1;
+ (id)formattedLogStringForSection:(id)arg1;
+ (id)boldAttributesForTranscript;
+ (id)attributesForTranscript;
+ (id)standardMonoSpaceFont;
+ (id)combinedCommandInvocationStringForLogSection:(id)arg1;
+ (id)tooltipForLogMessage:(id)arg1;
+ (id)lessUnderlinedWhiteImage;
+ (id)lessWhiteImage;
+ (id)moreUnderlinedWhiteImage;
+ (id)moreWhiteImage;
+ (id)lessUnderlinedImage;
+ (id)lessImage;
+ (id)moreUnderlinedImage;
+ (id)moreImage;
+ (id)newImageWithTitle:(id)arg1 selected:(BOOL)arg2 underlined:(BOOL)arg3;
+ (id)condensedOverImage;
+ (id)condensedDownImage;
+ (id)condensedUpImage;
+ (id)expandedOverImage;
+ (id)expandedDownImage;
+ (id)expandedUpImage;
+ (id)buildFileInProgressIconImage;
+ (id)buildFileErrorsIconImage;
+ (id)buildFileWarningsIconImage;
+ (id)buildFileAnalyzerResultsIconImage;
+ (id)buildFileWithIssuesIconImage;
+ (id)buildFileSuccessIconImage;
+ (id)fixItErrorIconImage;
+ (id)fixItWarningIconImage;
+ (id)errorIconImage;
+ (id)warningIconImage;
+ (id)analyzerControlFlowStepIconImage;
+ (id)analyzerStepIconImage;
+ (id)analyzerEventStepIconImage;
+ (id)analyzerResultIconImage;
+ (id)analyzerWarningIconImage;
+ (id)noticeIconImage;
+ (id)targetToolIconImage;
+ (id)targetLibraryIconImage;
+ (id)targetFrameworkIconImage;
+ (id)targetBundleIconImage;
+ (id)targetAppIconImage;
+ (id)targetIconImage;
+ (id)imageNamed:(id)arg1;
+ (id)sharedTextLayout;
@property(readonly, nonatomic) IDELogEditor *editor; // @synthesize editor=_editor;
@property(copy, nonatomic) NSString *searchFieldValue; // @synthesize searchFieldValue=_searchFieldValue;
@property(readonly, nonatomic) BOOL showAllResults; // @synthesize showAllResults=_showAllResults;
@property(readonly, nonatomic) BOOL showAnalyzerResults; // @synthesize showAnalyzerResults=_showAnalyzerResults;
@property(readonly, nonatomic) BOOL showErrors; // @synthesize showErrors=_showErrors;
@property(readonly, nonatomic) BOOL showWarnings; // @synthesize showWarnings=_showWarnings;
@property(readonly, nonatomic) BOOL showSteps; // @synthesize showSteps=_showSteps;
- (void)dealloc;
- (id)initWithEditor:(id)arg1 outlineView:(id)arg2 outlineIssuesView:(id)arg3;
- (void)clearOutlineLogic3;
- (void)selectMessage:(id)arg1 withinDataNode:(id)arg2;
- (void)selectMessageOrSection:(id)arg1 usingTranscript:(BOOL)arg2;
- (void)_delayedHighLightMessage:(id)arg1;
- (void)showFindIndicatorInSection:(id)arg1 withTranscriptTextRange:(struct _NSRange)arg2;
- (void)selectSection:(id)arg1 withTranscriptTextRange:(struct _NSRange)arg2;
- (void)selectMessageOrSection:(id)arg1;
- (BOOL)startingWithTextView:(id)arg1 findText:(id)arg2 ignoreCase:(BOOL)arg3 matchStyle:(long long)arg4 backwards:(BOOL)arg5 wrap:(BOOL)arg6;
- (id)transcriptAttributedStringForDataNode:(id)arg1;
- (id)transcriptStringForDataNode:(id)arg1;
- (void)updateSearchFieldValue:(id)arg1;
- (void)copyShownTranscripts:(id)arg1;
- (void)copyTranscriptToNewTextFile:(id)arg1;
- (BOOL)outlineView:(id)arg1 writeItems:(id)arg2 toPasteboard:(id)arg3;
- (id)attributedLogStringForItems:(id)arg1 inOutlineView:(id)arg2;
- (id)dataSource:(id)arg1 contextMenuForSelectedNodes:(id)arg2;
- (id)mentuItemTitleForCopyShownTranscripts;
- (id)localizedStringFor:(id)arg1 explanation:(id)arg2;
- (BOOL)dataSource:(id)arg1 filterDisplayedRootNode:(id)arg2;
- (void)jumpToSelection:(id)arg1;
- (BOOL)selectionContainsTranscripts;
- (void)collapseAllTranscripts:(id)arg1;
- (void)expandAllTranscripts:(id)arg1;
- (void)expandSelectedTranscripts:(BOOL)arg1;
- (void)expandTranscripts:(BOOL)arg1 nodes:(id)arg2;
- (void)_recursiveSetTextExpanded:(BOOL)arg1 inDataNode:(id)arg2;
- (void)_scrollToEnd:(id)arg1;
- (void)_recursiveReplaceAdapter:(id)arg1 with:(id)arg2 inDataNode:(id)arg3;
- (void)_updateRootsByIssues;
- (void)updateByIssueView:(id)arg1;
- (void)_updateIssuesForSection:(id)arg1 nodesToExpand:(id)arg2;
- (void)_updateIssuesForMessage:(id)arg1 nodesToExpand:(id)arg2;
- (id)nodeForIssueItem:(id)arg1;
- (id)categoryForItem:(id)arg1;
- (void)completeActivityLog;
- (void)testComputeCounts;
- (void)setExpandingWhileBuilding:(BOOL)arg1;
- (BOOL)expandingWhileBuilding;
- (void)buildOperationDidUpdateBuildLogItems:(id)arg1;
- (void)updateByStepView:(id)arg1;
- (id)textLayoutForDataNode:(id)arg1;
- (void)buildOperationDidUpdateBuildLogItems_addingChildrenInsteadOfReloading_Radar6707952:(id)arg1;
- (void)buildOperationDidUpdateBuildLogItems_addingChildrenInsteadOfReloading:(id)arg1;
- (id)nodeForLogItem:(id)arg1;
- (void)displayActivityLog:(id)arg1;
- (void)noteActiveViewDidChangeTo:(id)arg1;
- (void)setShowAllResults:(BOOL)arg1;
- (void)setShowSteps:(BOOL)arg1 showWarnings:(BOOL)arg2 showErrors:(BOOL)arg3 showAnalyzerResults:(BOOL)arg4;
- (void)_restoreConfigurationForCurrentOutlineView;
- (void)_saveConfigurationForCurrentOutlineView;
- (void)_rebuildOutline;
- (void)_updateCounts;
- (void)_updateRoots;
- (BOOL)shouldDisplaySummary;
- (void)_recursivelyExpandUnitTestNodesWithImportantMessagesForNode:(id)arg1;
- (id)activityLog;
- (void)scrollToEndOfOutline;
- (BOOL)shouldScrollToEndOfOutline;
- (void)scrollToEndOfOutlineView:(id)arg1;
- (BOOL)shouldScrollToEndOfOutlineView:(id)arg1;
- (BOOL)alwaysShowTargetInfo;
- (void)_configure;
- (id)_configureOutline:(id)arg1;
- (void)outlineIssuesSelectionChanged;
- (void)outlineSelectionChanged;
- (id)indexPathsForNodes:(id)arg1;
- (BOOL)filterLogItem:(id)arg1;
- (BOOL)filterLogMessage:(id)arg1;
- (BOOL)filterLogMessageSansSubitems:(id)arg1;
- (BOOL)filterLogSection:(id)arg1;
- (BOOL)logMessageHasFilteredSubItems:(id)arg1;
- (BOOL)logSectionHasFilteredSubItems:(id)arg1;
- (BOOL)iterateCountingOverSection:(id)arg1 errorCountPtr:(unsigned long long *)arg2 warningCountPtr:(unsigned long long *)arg3 analyzerCountPtr:(unsigned long long *)arg4 stopOnError:(BOOL)arg5 stopOnWarning:(BOOL)arg6 stopOnAnalyzer:(BOOL)arg7;
- (id)issueOccurrenceSubStepAdapter;
- (id)issueOccurrenceAdapter;
- (id)issueCategoryAdapter;
- (id)summaryItemAdapter;
- (id)noticeAdapter;
- (id)unitTestAdapter;
- (id)headerInclusionAdapter;
- (id)analyzerEventStepAdapter;
- (id)analyzerControlFlowStepAdapter;
- (id)analyzerStepAdapter;
- (id)analyzerResultAdapter;
- (id)analyzerWarningAdapter;
- (id)warningAdapter;
- (id)errorAdapter;
- (id)invocationAdapter;
- (id)sectionAdapter;
- (id)targetHeadingAdapter;
- (id)genericLogItemAdapter;

@end

@interface IDELogDocument : IDEEditorDocument <DVTTextFindable>
{
    IDEActivityLog *_activityLog;
}

@property(readonly) IDEActivityLog *buildLog; // @synthesize buildLog=_activityLog;
- (void)printDocument:(id)arg1;
- (id)findStringMatchingDescriptor:(id)arg1 backwards:(BOOL)arg2 from:(id)arg3 to:(id)arg4;
- (struct _NSRange)searchRangeforStartRange:(struct _NSRange)arg1 backwards:(BOOL)arg2 withinString:(id)arg3;
- (id)searchStringForLocation:(id)arg1;
- (id)findLocationFollowing:(id)arg1 backwards:(BOOL)arg2 passingTestForSection:(id)arg3;
- (id)lastLocationInLog;
- (id)lastIndexPathInSection:(id)arg1 inIndexPath:(id)arg2;
- (id)_iterateStartingWith:(id)arg1 section:(id)arg2 index:(unsigned long long)arg3 backwards:(BOOL)arg4 level:(long long)arg5 messageCount:(unsigned long long)arg6 onRefPath:(BOOL)arg7 passingTest:(id)arg8;
- (id)messageOrSectionForDocumentLocation:(id)arg1;
- (int)readOnlyStatus;
- (id)displayName;
- (id)initWithContentsOfURL:(id)arg1 ofType:(id)arg2 error:(id *)arg3;

// Remaining properties
@property unsigned long long supportedMatchingOptions;

@end

@interface IDELogGeniusResultsFinder : IDEGeniusResultsFinder
{
}

+ (Class)editorDocumentClass;
- (void)findGeniusResultsForEditorDocument:(id)arg1 selectedDocumentLocations:(id)arg2;

@end

@interface IDELogSubstructureItem : NSObject
{
    IDEActivityLog *_activityLog;
    IDELogDocumentLocation *_documentLocation;
    NSImage *_image;
}

@property(readonly) NSImage *image; // @synthesize image=_image;
@property(readonly) IDELogDocumentLocation *documentLocation; // @synthesize documentLocation=_documentLocation;
@property(readonly) IDEActivityLog *activityLog; // @synthesize activityLog=_activityLog;
- (BOOL)isEqual:(id)arg1;
- (long long)compare:(id)arg1;
- (id)ideModelObjectTypeIdentifier;
- (id)initWithActivityLog:(id)arg1 documentLocation:(id)arg2 image:(id)arg3;
- (BOOL)alwaysPassesFilter;
- (id)navigableItem_contentDocumentLocation;
- (id)navigableItem_documentType;
- (id)navigableItem_image;
- (id)navigableItem_name;

@end

@interface IDELogEditorScopeBar : DVTViewController <DVTScopeBarContentController>
{
    NSButton *_scopeLatestResultsButton;
    NSButton *_scopeAllResultsButton;
    NSButton *_scopeAllMessagesButton;
    NSButton *_scopeAllIssuesButton;
    NSButton *_scopeErrorsOnlyButton;
    NSSearchField *_scopeSearchField;
    id _delegate;
}

+ (id)defaultViewNibName;
@property id delegate; // @synthesize delegate=_delegate;
- (void)searchFieldAction:(id)arg1;
- (void)showErrorsOnly:(id)arg1;
- (void)showAllIssues:(id)arg1;
- (void)showAllMessages:(id)arg1;
- (void)showLatestResults:(id)arg1;
- (void)showAllResults:(id)arg1;
- (void)setScopeBarState:(int)arg1 showAllResults:(BOOL)arg2;
@property(readonly) double preferredViewHeight;

@end

@interface IDEActivityLogRecord (IDEActivityLogAdditions)
+ (id)keyPathsForValuesAffectingNavigableItem_progressValue;
@property(readonly) long long navigableItem_progressValue;
@end

@interface IDEKeyDrivenNavigableItem (IDEKitNavigableItemSourceControlCategories)
+ (id)keyPathsForValuesAffectingProgressValue;
- (long long)progressValue;
@end

