/*
 *     Generated by class-dump 3.3.3 (64 bit) (Debug version compiled Aug 11 2011 13:55:57).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#pragma mark Named Structures

struct CGPoint {
    double x;
    double y;
};

struct CGRect {
    struct CGPoint origin;
    struct CGSize size;
};

struct CGSize {
    double width;
    double height;
};

#pragma mark -

/*
 * File: /Developer/Library/Xcode/PrivatePlugIns/IDESymbolNavigator.ideplugin/Contents/MacOS/IDESymbolNavigator
 * UUID: EC8F5F18-70BC-3403-B50E-4E3A5563B8DB
 * Arch: Intel x86-64 (x86_64)
 *       Current version: 512.0.0, Compatibility version: 1.0.0
 *       Minimum Mac OS X version: 10.7.0
 *
 *       Objective-C Garbage Collection: Required
 */

@protocol DVTInvalidation <NSObject>
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly, getter=isValid) BOOL valid;
- (void)invalidate;
@end

@protocol DVTSourceExpressionSource <NSObject, DVTInvalidation>
@property(readonly) DVTSourceExpression *mouseOverExpression;
@property(readonly) struct CGRect currentSelectionFrame;
@property(readonly) DVTSourceExpression *contextMenuExpression;
@property(readonly) DVTSourceExpression *selectedExpression;

@optional
@property(readonly) DVTSourceExpression *quickHelpExpression;
- (void)unregisterMouseOverExpressionObserver:(id)arg1;
- (void)registerMouseOverExpressionObserver:(id)arg1;
- (void)unregisterSelectedExpressionObserver:(id)arg1;
- (void)registerSelectedExpressionObserver:(id)arg1;
@end

@protocol IDEIndexSymbolSelectionSource
- (id)selectedSymbols;
@end

@protocol IDESourceExpressionSource <DVTSourceExpressionSource>
- (BOOL)expressionContainsExecutableCode:(id)arg1;
- (BOOL)isExpressionFunctionOrMethodCall:(id)arg1;
- (BOOL)isExpressionInFunctionOrMethodBody:(id)arg1;
- (BOOL)isExpressionFunctionOrMethodDefinition:(id)arg1;
- (BOOL)isExpressionWithinComment:(id)arg1;
- (void)symbolsForExpression:(id)arg1 inQueue:(struct dispatch_queue_s *)arg2 completionBlock:(id)arg3;

@optional
- (id)importStringInExpression:(id)arg1;
@end

@protocol NSCopying
- (id)copyWithZone:(struct _NSZone *)arg1;
@end

@protocol NSObject
- (id)description;
- (unsigned long long)retainCount;
- (id)autorelease;
- (oneway void)release;
- (id)retain;
- (BOOL)respondsToSelector:(SEL)arg1;
- (BOOL)conformsToProtocol:(id)arg1;
- (BOOL)isMemberOfClass:(Class)arg1;
- (BOOL)isKindOfClass:(Class)arg1;
- (BOOL)isProxy;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2 withObject:(id)arg3;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2;
- (id)performSelector:(SEL)arg1;
- (struct _NSZone *)zone;
- (id)self;
- (Class)class;
- (Class)superclass;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
@end

@interface IDESymbolNavigatorFilterPredicate : NSPredicate <NSCopying>
{
    NSSet *_symbolIDs;
}

- (BOOL)evaluateWithObject:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithSymbolIdentifers:(id)arg1;

@end

@interface IDESymbolNavigator : IDENavigator <IDEIndexSymbolSelectionSource, IDESourceExpressionSource>
{
    NSTableColumn *mainTableColumn;
    IDENavigatorOutlineView *outlineView;
    id _indexingFinishedObserver;
    id <DVTObservingToken> _outlineViewSelectedObjectsObserver;
    id <IDEOpenRequest> _lastOpenRequest;
    DVTSourceExpression *_selectedExpression;
    DVTSourceExpression *_mouseOverExpression;
    struct CGRect _currentSelectionFrame;
    NSCell *_symbolCell;
    NSCell *_lozengeCell;
    NSArray *_objects;
    NSSet *_expandedItems;
    NSArray *_selectedObjects;
    NSString *_symbolNamePatternString;
    NSSet *_parentsForFiltering;
    NSArray *_expandedIdentifiersBeforeFiltering;
    NSDictionary *_previouslyRestoredStateDictionary;
    NSArray *_savedItemsToSelect;
    NSArray *_savedItemsToExpand;
    DVTDispatchLock *_accessLock;
    unsigned long long _currentGeneration;
    long long _loadingProgress;
    BOOL _restoringState;
    BOOL _showWorkspaceOnly;
    BOOL _showContainersOnly;
    BOOL _showHierarchy;
    BOOL _showClassesOnly;
}

+ (void)configureStateSavingObjectPersistenceByName:(id)arg1;
+ (void)initialize;
@property(readonly) long long loadingProgress; // @synthesize loadingProgress=_loadingProgress;
@property(copy) NSSet *parentsForFiltering; // @synthesize parentsForFiltering=_parentsForFiltering;
@property id <IDEOpenRequest> lastOpenRequest; // @synthesize lastOpenRequest=_lastOpenRequest;
@property BOOL showClassesOnly; // @synthesize showClassesOnly=_showClassesOnly;
@property BOOL showHierarchy; // @synthesize showHierarchy=_showHierarchy;
@property BOOL showContainersOnly; // @synthesize showContainersOnly=_showContainersOnly;
@property BOOL showWorkspaceOnly; // @synthesize showWorkspaceOnly=_showWorkspaceOnly;
@property(retain) NSString *symbolNamePatternString; // @synthesize symbolNamePatternString=_symbolNamePatternString;
@property(retain) NSArray *selectedObjects; // @synthesize selectedObjects=_selectedObjects;
@property DVTSourceExpression *mouseOverExpression; // @synthesize mouseOverExpression=_mouseOverExpression;
@property struct CGRect currentSelectionFrame; // @synthesize currentSelectionFrame=_currentSelectionFrame;
@property(retain) NSArray *objects; // @synthesize objects=_objects;
@property DVTSourceExpression *selectedExpression; // @synthesize selectedExpression=_selectedExpression;
- (void)revealNavigableItems:(id)arg1;
- (void)revealNavigableItemsWithIdentifiers:(id)arg1 identifiersToExpand:(id)arg2 generation:(unsigned long long)arg3;
- (id)findNavigableItemsInItems:(id)arg1 withIdentifiers:(id)arg2 includeParents:(BOOL)arg3;
- (id)filterDefinitionIdentifier;
- (void)updateFilterPredicate;
- (void)revertState;
- (id)outlineView:(id)arg1 dataCellForTableColumn:(id)arg2 item:(id)arg3;
- (id)lozengeCell;
- (id)symbolCell;
- (void)outlineViewItemDidCollapse:(id)arg1;
- (void)outlineViewItemDidExpand:(id)arg1;
- (BOOL)outlineView:(id)arg1 shouldEditTableColumn:(id)arg2 item:(id)arg3;
- (id)outlineView:(id)arg1 selectionIndexesForProposedSelection:(id)arg2;
- (BOOL)outlineView:(id)arg1 isGroupHeaderItem:(id)arg2;
- (void)openDoubleClickedNavigableItemsAction:(id)arg1;
- (void)openClickedNavigableItemAction:(id)arg1;
- (void)openSelectedNavigableItemsKeyAction:(id)arg1;
- (id)openSpecifierForNavigableItem:(id)arg1 error:(id *)arg2;
- (void)showQuickHelpForCurrentSelection:(id)arg1;
- (void)_updateSelectedExpressionInfo;
@property(readonly) DVTSourceExpression *contextMenuExpression;
- (id)_resolvedLocation:(id)arg1 symbol:(id)arg2;
- (void)symbolsForExpression:(id)arg1 inQueue:(struct dispatch_queue_s *)arg2 completionBlock:(id)arg3;
- (BOOL)expressionContainsExecutableCode:(id)arg1;
- (BOOL)isExpressionFunctionOrMethodCall:(id)arg1;
- (BOOL)isExpressionInFunctionOrMethodBody:(id)arg1;
- (BOOL)isExpressionFunctionOrMethodDefinition:(id)arg1;
- (BOOL)isExpressionWithinComment:(id)arg1;
- (BOOL)canBecomeMainViewController;
- (id)expandedIdentifiers;
- (id)selectedSymbolIdentifiers;
@property(readonly) NSArray *selectedSymbols;
- (void)cancelOperations;
- (void)_refreshBrowser;
- (id)domainIdentifier;
- (id)contextMenuSelection;
- (void)setOutputSelection:(id)arg1;
@property(copy) NSString *visibleRectString;
- (void)commitStateToDictionary:(id)arg1;
- (void)revertStateWithDictionary:(id)arg1;
- (id)allParentsOfSymbols:(id)arg1 generation:(unsigned long long)arg2;
- (id)dvtExtraBindings;
- (BOOL)isCurrentGeneration:(unsigned long long)arg1;
@property(readonly) unsigned long long currentGeneration; // @dynamic currentGeneration;
- (BOOL)delegateFirstResponder;
- (void)invalidate;
- (void)viewWillUninstall;
- (void)viewDidInstall;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)loadView;
- (void)_outlineViewSelectionChangedWithDictionary:(id)arg1;

// Remaining properties
@property(copy) NSSet *expandedItems; // @dynamic expandedItems;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly) NSMutableSet *mutableExpandedItems; // @dynamic mutableExpandedItems;
@property(readonly) DVTSourceExpression *quickHelpExpression;
@property(readonly, getter=isValid) BOOL valid;

@end

@interface IDESymbolNavigatorRootGroup : NSObject
{
    NSOperationQueue *_queue;
    NSArray *_groups;
    IDEWorkspace *_workspace;
    IDESymbolNavigator *_navigator;
    unsigned long long _generation;
}

@property(readonly) NSOperationQueue *queue; // @synthesize queue=_queue;
- (void)fetchSymbols:(id)arg1 generation:(unsigned long long)arg2 lastOperation:(id)arg3;
- (id)groups;
- (void)cancelOperations;
- (void)setSymbolNavigator:(id)arg1 identifiersToSelect:(id)arg2 identifiersToExpand:(id)arg3;
- (void)childrenWithNavigator:(id)arg1 identifiersToSelect:(id)arg2 identifiersToExpand:(id)arg3;
- (id)navigatorSymbolForIndexSymbol:(id)arg1 withNavigator:(id)arg2;
- (id)initWithWorkspace:(id)arg1;

@end

@interface IDESymbolNavigatorOutlineView : IDENavigatorOutlineView
{
}

- (id)parentForItem:(id)arg1;

@end

@interface IDENavigableItemSymbolsDomainProvider : IDENavigableItemDomainProvider
{
}

+ (id)domainObjectForWorkspace:(id)arg1;

@end

@interface IDESymbolNavigatorSymbol : NSObject
{
    IDEIndexSymbol *_symbol;
}

@property(readonly) IDEIndexSymbol *symbol; // @synthesize symbol=_symbol;
- (void)fetchSymbols:(id)arg1 generation:(unsigned long long)arg2 lastOperation:(id)arg3;
- (id)ideModelObjectTypeIdentifier;
- (id)navigableItem_documentType;
- (id)navigableItem_contentDocumentLocation;
- (id)navigableItem_image;
- (id)navigableItem_name;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (id)initWithSymbol:(id)arg1;

@end

@interface IDESymbolNavigatorClassSymbol : NSObject
{
    NSOperationQueue *_queue;
    unsigned long long _generation;
    IDESymbolNavigator *_navigator;
    IDEIndexClassSymbol *_symbol;
    NSArray *_children;
    NSMutableArray *_newChildren;
    DVTDispatchLock *_accessLock;
}

@property(readonly) IDEIndexClassSymbol *symbol; // @synthesize symbol=_symbol;
- (id)ideModelObjectTypeIdentifier;
- (id)navigableItem_documentType;
- (id)navigableItem_contentDocumentLocation;
- (id)navigableItem_image;
- (id)navigableItem_name;
- (void)fetchSymbols:(id)arg1 generation:(unsigned long long)arg2 lastOperation:(id)arg3;
- (id)children;
- (id)loadChildrenWithOperation:(id)arg1;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (id)initWithClassSymbol:(id)arg1 operationQueue:(id)arg2 generation:(unsigned long long)arg3 symbolNavigator:(id)arg4;

@end

@interface IDESymbolNavigatorGroup : NSObject
{
    NSOperationQueue *_queue;
    NSArray *_children;
    NSArray *_newChildren;
    NSString *_subtitle;
    unsigned long long _generation;
    IDESymbolNavigator *_navigator;
}

- (id)navigableItem_image;
@property(readonly) NSString *symbolKindIdentifier;
- (void)fetchSymbols:(id)arg1 lastOperation:(id)arg2;
- (id)children;
- (void)refreshWithIndex:(id)arg1 generation:(unsigned long long)arg2 lastOperation:(id)arg3;
- (void)refreshWithIndex:(id)arg1 lastOperation:(id)arg2;
- (id)childrenWithIndex:(id)arg1;
- (id)unsortedSymbolsWithIndex:(id)arg1;
- (id)ideModelObjectTypeIdentifier;
- (id)navigableItem_documentType;
- (id)navigableItem_contentDocumentLocation;
- (id)calculateSubtitleWithIndex:(id)arg1;
- (id)navigatorSymbolForIndexSymbol:(id)arg1;
@property(readonly) NSString *subtitle;
- (id)navigableItem_name;
@property(readonly) BOOL isInProject;
- (id)initWithOperationQueue:(id)arg1 generation:(unsigned long long)arg2 symbolNavigator:(id)arg3;

@end

@interface IDESymbolNavigatorClassesGroup : IDESymbolNavigatorGroup
{
}

- (id)unsortedSymbolsWithIndex:(id)arg1;
- (id)ideModelObjectTypeIdentifier;
- (id)symbolKindIdentifier;
- (id)navigableItem_name;

@end

@interface IDESymbolNavigatorProtocolsGroup : IDESymbolNavigatorGroup
{
}

- (id)unsortedSymbolsWithIndex:(id)arg1;
- (id)ideModelObjectTypeIdentifier;
- (id)symbolKindIdentifier;
- (id)navigableItem_name;

@end

@interface IDESymbolNavigatorFunctionsGroup : IDESymbolNavigatorGroup
{
}

- (id)ideModelObjectTypeIdentifier;
- (id)symbolKindIdentifier;
- (id)navigableItem_name;

@end

@interface IDESymbolNavigatorStructsGroup : IDESymbolNavigatorGroup
{
}

- (id)ideModelObjectTypeIdentifier;
- (id)symbolKindIdentifier;
- (id)navigableItem_name;

@end

@interface IDESymbolNavigatorUnionsGroup : IDESymbolNavigatorGroup
{
}

- (id)symbolKindIdentifier;
- (id)ideModelObjectTypeIdentifier;
- (id)navigableItem_name;

@end

@interface IDESymbolNavigatorEnumsGroup : IDESymbolNavigatorGroup
{
}

- (id)ideModelObjectTypeIdentifier;
- (id)symbolKindIdentifier;
- (id)navigableItem_name;

@end

@interface IDESymbolNavigatorTypesGroup : IDESymbolNavigatorGroup
{
}

- (id)ideModelObjectTypeIdentifier;
- (id)symbolKindIdentifier;
- (id)navigableItem_name;

@end

@interface IDESymbolNavigatorGlobalsGroup : IDESymbolNavigatorGroup
{
}

- (id)ideModelObjectTypeIdentifier;
- (id)symbolKindIdentifier;
- (id)navigableItem_name;

@end

@interface IDESymbolNavigatorGroupNavigableItem : IDEKeyDrivenNavigableItem
{
}

+ (id)keyPathsForValuesAffectingSubtitle;
- (BOOL)isMajorGroup;
- (id)subtitle;

@end

@interface IDESymbolNavigatorProtocolSymbol : NSObject
{
    NSOperationQueue *_queue;
    unsigned long long _generation;
    IDESymbolNavigator *_navigator;
    IDEIndexProtocolSymbol *_symbol;
    NSArray *_children;
    NSMutableArray *_newChildren;
    DVTDispatchLock *_accessLock;
}

@property(readonly) IDEIndexProtocolSymbol *symbol; // @synthesize symbol=_symbol;
- (id)ideModelObjectTypeIdentifier;
- (id)navigableItem_documentType;
- (id)navigableItem_contentDocumentLocation;
- (id)navigableItem_image;
- (id)navigableItem_name;
- (void)fetchSymbols:(id)arg1 generation:(unsigned long long)arg2 lastOperation:(id)arg3;
- (id)children;
- (id)loadChildrenWithOperation:(id)arg1;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (id)initWithProtocolSymbol:(id)arg1 operationQueue:(id)arg2 generation:(unsigned long long)arg3 symbolNavigator:(id)arg4;

@end

@interface IDESymbolNavigatorCategorySymbol : NSObject
{
    NSOperationQueue *_queue;
    unsigned long long _generation;
    IDESymbolNavigator *_navigator;
    IDEIndexCategorySymbol *_symbol;
    NSArray *_children;
    NSMutableArray *_newChildren;
    DVTDispatchLock *_accessLock;
}

@property(readonly) IDEIndexCategorySymbol *symbol; // @synthesize symbol=_symbol;
- (id)ideModelObjectTypeIdentifier;
- (id)navigableItem_documentType;
- (id)navigableItem_contentDocumentLocation;
- (id)navigableItem_image;
- (id)navigableItem_name;
- (void)fetchSymbols:(id)arg1 generation:(unsigned long long)arg2 lastOperation:(id)arg3;
- (id)children;
- (id)loadChildrenWithOperation:(id)arg1;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (id)initWithCategorySymbol:(id)arg1 operationQueue:(id)arg2 generation:(unsigned long long)arg3 symbolNavigator:(id)arg4;

@end

@interface IDESymbolNavigatorContainerSymbol : NSObject
{
    NSOperationQueue *_queue;
    unsigned long long _generation;
    IDESymbolNavigator *_navigator;
    IDEIndexContainerSymbol *_symbol;
    NSArray *_children;
    NSString *_cachedName;
    DVTDispatchLock *_accessLock;
}

@property(readonly) IDEIndexContainerSymbol *symbol; // @synthesize symbol=_symbol;
- (id)ideModelObjectTypeIdentifier;
- (id)navigableItem_documentType;
- (id)navigableItem_contentDocumentLocation;
- (id)navigableItem_image;
- (id)navigableItem_name;
- (void)fetchSymbols:(id)arg1 generation:(unsigned long long)arg2 lastOperation:(id)arg3;
- (id)children;
- (void)loadChildrenWithOperation:(id)arg1;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (id)initWithContainerSymbol:(id)arg1 operationQueue:(id)arg2 generation:(unsigned long long)arg3 symbolNavigator:(id)arg4;

@end

