/*
 *     Generated by class-dump 3.3.3 (64 bit) (Debug version compiled Aug 11 2011 13:55:57).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#pragma mark Named Structures

struct _NSRange {
    unsigned long long _field1;
    unsigned long long _field2;
};

#pragma mark Typedef'd Structures

typedef struct {
    unsigned long long location;
    unsigned long long length;
} CDStruct_91ee6ea3;

#pragma mark -

/*
 * File: /Developer/Library/Xcode/PrivatePlugIns/HexEditor.ideplugin/Contents/MacOS/HexEditor
 * UUID: 6FE56852-C0A5-3481-A17B-93D59071AD01
 * Arch: Intel x86-64 (x86_64)
 *       Current version: 510.0.0, Compatibility version: 1.0.0
 *       Minimum Mac OS X version: 10.7.0
 *
 *       Objective-C Garbage Collection: Required
 */

@protocol DVTFindBarFindable

@optional
- (id)startingLocationForFindBar:(id)arg1 findingBackwards:(BOOL)arg2;
- (void)dvtFindBar:(id)arg1 didUpdateCurrentResult:(id)arg2;
- (void)dvtFindBar:(id)arg1 didUpdateResults:(id)arg2;
@end

@protocol DVTTextFindable <NSObject>
- (id)findStringMatchingDescriptor:(id)arg1 backwards:(BOOL)arg2 from:(id)arg3 to:(id)arg4;

@optional
@property unsigned long long supportedMatchingOptions;
@end

@protocol NSObject
- (id)description;
- (unsigned long long)retainCount;
- (id)autorelease;
- (oneway void)release;
- (id)retain;
- (BOOL)respondsToSelector:(SEL)arg1;
- (BOOL)conformsToProtocol:(id)arg1;
- (BOOL)isMemberOfClass:(Class)arg1;
- (BOOL)isKindOfClass:(Class)arg1;
- (BOOL)isProxy;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2 withObject:(id)arg3;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2;
- (id)performSelector:(SEL)arg1;
- (struct _NSZone *)zone;
- (id)self;
- (Class)class;
- (Class)superclass;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
@end

@interface IDEHexEditorDocument : IDEEditorDocument
{
    HFByteArray *_byteArray;
}

+ (BOOL)isNativeType:(id)arg1;
@property(readonly) HFByteArray *byteArray; // @synthesize byteArray=_byteArray;
- (id)ideTopLevelStructureObjects;
- (BOOL)writeToURL:(id)arg1 ofType:(id)arg2 error:(id *)arg3;
- (BOOL)readFromData:(id)arg1 ofType:(id)arg2 error:(id *)arg3;
- (BOOL)readFromURL:(id)arg1 ofType:(id)arg2 error:(id *)arg3;
- (BOOL)canSave;

@end

@interface IDEHexEditor : IDEEditor <DVTTextFindable, DVTFindBarFindable>
{
    HFTextView *_hexView;
    HFLineCountingRepresenter *_lineNumberRepresenter;
    HFHexTextRepresenter *_hexRepresenter;
    HFStringEncodingTextRepresenter *_textRepresenter;
    id <DVTObservingToken> _stateChangeObserverToken;
    BOOL _haveRegisteredClassSpecificDefaults;
}

+ (void)foo;
+ (void)configureStateSavingObjectPersistenceByName:(id)arg1;
+ (unsigned long long)defaultLineNumberFormat;
+ (id)lineNumberFormatStateKey;
+ (void)initialize;
@property(readonly) HFStringEncodingTextRepresenter *textRepresenter; // @synthesize textRepresenter=_textRepresenter;
@property(readonly) HFHexTextRepresenter *hexRepresenter; // @synthesize hexRepresenter=_hexRepresenter;
@property(readonly) HFLineCountingRepresenter *lineNumberRepresenter; // @synthesize lineNumberRepresenter=_lineNumberRepresenter;
@property(readonly) HFTextView *hexView; // @synthesize hexView=_hexView;
- (void)revertStateWithDictionary:(id)arg1;
- (void)commitStateToDictionary:(id)arg1;
- (void)byteGrouping32:(id)arg1;
- (void)byteGrouping16:(id)arg1;
- (void)byteGrouping8:(id)arg1;
- (void)byteGrouping4:(id)arg1;
- (void)byteGrouping2:(id)arg1;
- (void)byteGroupingNone:(id)arg1;
- (void)plainText:(id)arg1;
- (void)hexadecimal:(id)arg1;
- (void)lineNumbers:(id)arg1;
- (void)extendSelection:(id)arg1;
- (void)moveSelection:(id)arg1;
- (void)toggleOverwriteMode:(id)arg1;
- (BOOL)validateMenuItem:(id)arg1;
@property(readonly) HFLayoutRepresenter *layoutRepresenter;
@property(readonly) HFController *controller;
- (id)startingLocationForFindBar:(id)arg1 findingBackwards:(BOOL)arg2;
- (void)dvtFindBar:(id)arg1 didUpdateCurrentResult:(id)arg2;
- (id)_interpretStringAsHexBytes:(id)arg1;
- (BOOL)_isSearchResultRangeValid:(struct _NSRange)arg1;
- (BOOL)_isSearchResultValid:(unsigned long long)arg1;
- (struct _NSRange)_findData:(id)arg1 inRange:(CDStruct_91ee6ea3)arg2 forwards:(BOOL)arg3;
- (struct _NSRange)_findStringAsHex:(id)arg1 inRange:(CDStruct_91ee6ea3)arg2 forwards:(BOOL)arg3;
- (struct _NSRange)_findStringAsText:(id)arg1 inRange:(CDStruct_91ee6ea3)arg2 forwards:(BOOL)arg3;
- (struct _NSRange)_findString:(id)arg1 inRange:(CDStruct_91ee6ea3)arg2 forwards:(BOOL)arg3;
- (id)findStringMatchingDescriptor:(id)arg1 backwards:(BOOL)arg2 from:(id)arg3 to:(id)arg4;
- (void)setLineNumberFormat:(unsigned long long)arg1;
- (void)setStartingLineNumber:(unsigned long long)arg1;
@property unsigned long long bytesPerColumn;
- (void)_setRepresenter:(id)arg1 showing:(BOOL)arg2;
- (BOOL)_togglRepresenterShowing:(id)arg1;
- (BOOL)_isRepresenterShowing:(id)arg1;
- (id)_representerForClass:(Class)arg1;
- (void)takeFocus;
- (void)_storeLineNumberFormatPreference:(id)arg1;
- (void)_restorePreferences;
- (id)_createLineCounterRepresenter;
- (void)_registerClassSpecificDefaults;
@property unsigned long long supportedMatchingOptions;
- (void)invalidate;
- (void)loadView;

@end

@interface IDEHexEditorDocumentLocation : DVTDocumentLocation
{
    CDStruct_91ee6ea3 _range;
}

- (long long)compare:(id)arg1;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithDocumentURL:(id)arg1 range:(CDStruct_91ee6ea3)arg2;
- (id)initWithDocumentURL:(id)arg1 timestamp:(id)arg2 range:(CDStruct_91ee6ea3)arg3;
- (void)setRange:(CDStruct_91ee6ea3)arg1;
- (CDStruct_91ee6ea3)range;

@end

@interface IDEHexEditorNavigable : NSObject
{
    CDStruct_91ee6ea3 _range;
    IDEHexEditorDocument *_document;
}

@property IDEHexEditorDocument *document; // @synthesize document=_document;
- (id)ideModelObjectTypeIdentifier;
- (id)navigableItem_fileReference;
- (id)navigableItem_documentType;
- (id)navigableItem_image;
- (id)navigableItem_name;
- (id)navigableItem_contentDocumentLocation;
- (void)setRange:(CDStruct_91ee6ea3)arg1;
- (CDStruct_91ee6ea3)range;

@end

