/*
 *     Generated by class-dump 3.3.3 (64 bit) (Debug version compiled Aug 11 2011 13:55:57).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#pragma mark -

/*
 * File: /Developer/Library/Xcode/PrivatePlugIns/IDEModelFoundation.ideplugin/Contents/MacOS/IDEModelFoundation
 * UUID: 48D9AF4D-530B-387A-93C5-90C98329E1C7
 * Arch: Intel x86-64 (x86_64)
 *       Current version: 562.0.0, Compatibility version: 1.0.0
 *       Minimum Mac OS X version: 10.7.0
 *
 *       Objective-C Garbage Collection: Required
 */

@protocol CDMIdentification <NSObject>
@property(copy) NSNumber *uniqueID;
@property(copy) NSString *name;
@end

@protocol IDEBlueprintProvider <NSObject>
- (id)testableProdiver;
- (id)blueprintForName:(id)arg1;
- (id)blueprintForIdentifier:(id)arg1;
- (id)organizationName;
- (id)name;
- (id)blueprints;
@end

@protocol IDEInspectorAccessibilitySupport <NSObject>
- (id)humanReadableNameForInspectorKeyPath:(id)arg1;
@end

@protocol IDEInspectorMatching <NSObject>
- (id)applicableInspectorsForCategory:(id)arg1 suggestion:(id)arg2;
@end

@protocol NSCoding
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
@end

@protocol NSObject
- (id)description;
- (unsigned long long)retainCount;
- (id)autorelease;
- (oneway void)release;
- (id)retain;
- (BOOL)respondsToSelector:(SEL)arg1;
- (BOOL)conformsToProtocol:(id)arg1;
- (BOOL)isMemberOfClass:(Class)arg1;
- (BOOL)isKindOfClass:(Class)arg1;
- (BOOL)isProxy;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2 withObject:(id)arg3;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2;
- (id)performSelector:(SEL)arg1;
- (struct _NSZone *)zone;
- (id)self;
- (Class)class;
- (Class)superclass;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
@end

@protocol XDErrorWarningCallback <NSObject>
- (BOOL)didSucceed;
- (BOOL)shouldContinue;
- (id)targetVersion;
- (id)compilerFlags;
- (id)descriptionForElement:(id)arg1;
- (void)createWarningForElement:(id)arg1 withFormat:(id)arg2 category:(int)arg3 documentURL:(id)arg4;
- (void)createWarningForElement:(id)arg1 withMessage:(id)arg2 category:(int)arg3 documentURL:(id)arg4;
- (void)createErrorForElement:(id)arg1 withFormat:(id)arg2 category:(int)arg3 documentURL:(id)arg4;
- (void)createErrorForElement:(id)arg1 withMessage:(id)arg2 category:(int)arg3 documentURL:(id)arg4;
@end

@protocol XDMappingCompilerCallback
- (id)targetVersion;
- (BOOL)continueGeneration;
- (void)addWarningForElement:(id)arg1 prefix:(id)arg2 message:(id)arg3 category:(int)arg4;
- (void)addErrorForElement:(id)arg1 prefix:(id)arg2 message:(id)arg3 category:(int)arg4;
@end

@protocol XDUMLAbstraction <XDUMLDependency>
- (void)addClient:(id)arg1;
- (void)addSupplier:(id)arg1;
@end

@protocol XDUMLAssociation <XDUMLClassifier, XDUMLRelationship>
- (void)addMemberEnd:(id)arg1;
- (id)ownedEnds;
- (id)memberEnds;
- (BOOL)isDerived;
@end

@protocol XDUMLBehavioralFeature <XDUMLFeature, XDUMLNamespace>
- (id)raisedExceptions;
- (id)returnResult;
- (id)formalParameters;
- (id)parameters;
@end

@protocol XDUMLBehavioredClassifier <XDUMLClassInterfaceCommons>
- (id)newImplementationOf:(id)arg1;
- (void)implementationRemoved:(id)arg1;
- (void)implementationAdded:(id)arg1;
- (id)implementations;
@end

@protocol XDUMLClass <XDUMLBehavioredClassifier>
- (void)setParentClass:(id)arg1;
- (id)parentClass;
- (id)superClasses;
- (id)ownedOperations;
- (id)ownedAttributes;
@end

@protocol XDUMLClassInterfaceCommons <XDUMLClassifier>
@end

@protocol XDUMLClassifier <XDUMLNamespace, XDUMLType>
- (void)specializationRemoved:(id)arg1;
- (void)specializationAdded:(id)arg1;
- (id)specializations;
- (id)newGeneralizationFrom:(id)arg1;
- (void)generalizationRemoved:(id)arg1;
- (void)generalizationAdded:(id)arg1;
- (id)newOperationWithName:(id)arg1;
- (id)operationForName:(id)arg1;
- (void)removeOperation:(id)arg1;
- (void)addOperation:(id)arg1;
- (id)newPropertyWithName:(id)arg1;
- (id)propertyForName:(id)arg1;
- (void)removeProperty:(id)arg1;
- (void)addProperty:(id)arg1;
- (void)removeObjectFromPropertiesAtIndex:(unsigned long long)arg1;
- (void)insertObject:(id)arg1 inPropertiesAtIndex:(unsigned long long)arg2;
- (id)properties;
- (id)ownedOperations;
- (id)ownedAttributes;
- (void)setIsAbstract:(BOOL)arg1;
- (id)attributes;
- (BOOL)isAbstract;
- (id)generalizations;
- (id)features;
@end

@protocol XDUMLComment <XDUMLElement>
- (void)removeObjectFromAnnotatedElementsAtIndex:(unsigned long long)arg1;
- (void)insertObject:(id)arg1 inAnnotatedElementsAtIndex:(unsigned long long)arg2;
- (void)setBody:(id)arg1;
- (id)annotatedElements;
- (id)body;
@end

@protocol XDUMLDataType <XDUMLClassifier>
- (id)ownedOperations;
- (id)ownedAttributes;
@end

@protocol XDUMLDependency <XDUMLDirectedRelationship, XDUMLPackageableElement>
- (id)suppliers;
- (id)clients;
@end

@protocol XDUMLDirectedRelationship <XDUMLRelationship>
- (id)targets;
- (id)sources;
@end

@protocol XDUMLElement <NSObject>
- (id)elementForName:(id)arg1 inBucketNamed:(id)arg2;
- (id)elementsInAllBuckets;
- (unsigned long long)elementsCountInBucketNamed:(id)arg1;
- (id)elementsInBucketNamed:(id)arg1;
- (unsigned long long)indexForElement:(id)arg1 inBucketNamed:(id)arg2;
- (void)removeElementAtIndex:(unsigned long long)arg1 fromBucketNamed:(id)arg2;
- (void)removeElement:(id)arg1 fromBucketNamed:(id)arg2;
- (void)addElement:(id)arg1 toBucketNamed:(id)arg2 atIndex:(unsigned long long)arg3;
- (void)deleteElementsBucketWithName:(id)arg1;
- (void)createElementsBucketWithName:(id)arg1 allowsDuplicates:(BOOL)arg2 preserveInsertOrder:(BOOL)arg3;
- (void)setUniqueElementID:(id)arg1;
- (id)createUniqueElementID;
- (id)uniqueElementID;
- (id)newStereotypeWithName:(id)arg1;
- (void)removeStereotype:(id)arg1;
- (void)addStereotype:(id)arg1;
- (id)stereotypes;
- (void)removeObjectFromOwnedCommentsAtIndex:(unsigned long long)arg1;
- (void)insertObject:(id)arg1 inOwnedCommentsAtIndex:(unsigned long long)arg2;
- (void)setOwner:(id)arg1;
- (id)ownedComments;
- (id)owner;
- (id)ownedElements;
@end

@protocol XDUMLEnumeration <XDUMLDataType>
- (id)newLiteralWithName:(id)arg1;
- (id)ownedLiterals;
@end

@protocol XDUMLFeature <XDUMLRedefinableElement>
- (void)setIsStatic:(BOOL)arg1;
- (BOOL)isStatic;
- (id)featuringClassifiers;
@end

@protocol XDUMLGeneralization <XDUMLDirectedRelationship>
- (void)setSpecific:(id)arg1;
- (void)setGeneral:(id)arg1;
- (void)remove;
- (id)specific;
- (id)general;
@end

@protocol XDUMLImplementation <XDUMLClassifier>
- (void)setContract:(id)arg1;
- (void)remove;
- (id)implementingClassifier;
- (id)contract;
@end

@protocol XDUMLInterface <XDUMLClassInterfaceCommons>
- (void)implementorRemoved:(id)arg1;
- (void)implementorAdded:(id)arg1;
- (id)implementors;
- (id)redefinedInterface;
- (id)nestedInterface;
- (id)ownedOperations;
- (id)ownedAttributes;
@end

@protocol XDUMLMultiplicityElement <XDUMLElement>
- (long long)upper;
- (long long)lower;
- (BOOL)isUnique;
- (BOOL)isOrdered;
@end

@protocol XDUMLNamedElement <XDUMLElement>
- (void)removeContainingBucket:(id)arg1;
- (void)addContainingBucket:(id)arg1;
- (void)setVisibility:(unsigned long long)arg1;
- (void)setName:(id)arg1;
- (id)separator;
- (unsigned long long)visibility;
- (id)namespace;
- (id)qualifiedName;
- (id)name;
@end

@protocol XDUMLNamespace <XDUMLNamedElement>
- (id)ownedMembers;
- (id)members;
@end

@protocol XDUMLOperation <XDUMLBehavioralFeature, XDUMLNamespace>
- (void)setOwnedParameters:(id)arg1;
- (void)setIsLeaf:(BOOL)arg1;
- (void)setIsQuery:(BOOL)arg1;
- (id)newReturnParameterWithType:(id)arg1;
- (id)newParameterWithName:(id)arg1;
- (id)type;
- (id)redefinedOperations;
- (long long)upper;
- (long long)lower;
- (BOOL)isUnique;
- (BOOL)isQuery;
- (BOOL)isOrdered;
- (id)raisedExceptions;
- (id)ownedParameters;
- (id)ownerClass;
@end

@protocol XDUMLPackage <XDUMLNamedElement, XDUMLNamespace>
- (id)packageAtQualifierPath:(id)arg1 forceCreation:(BOOL)arg2;
- (void)setModel:(id)arg1;
- (id)model;
- (void)removePackage:(id)arg1;
- (id)packageForName:(id)arg1;
- (void)addPackage:(id)arg1 toQualifierPath:(id)arg2;
- (id)dataTypeForName:(id)arg1;
- (void)addDataType:(id)arg1 toQualifierPath:(id)arg2;
- (id)allInterfaces;
- (void)removeInterface:(id)arg1;
- (id)interfaceForName:(id)arg1;
- (void)addInterface:(id)arg1 toQualifierPath:(id)arg2;
- (id)allClasses;
- (void)removeClass:(id)arg1;
- (id)classForName:(id)arg1;
- (void)addClass:(id)arg1 toQualifierPath:(id)arg2;
- (void)addType:(id)arg1;
- (id)nestingPackage;
- (id)nestedPackages;
- (id)ownedTypes;
@end

@protocol XDUMLPackageableElement <XDUMLNamedElement>
- (unsigned long long)visibility;
@end

@protocol XDUMLParameter <XDUMLTypedElement>
- (void)setDirection:(unsigned long long)arg1;
- (unsigned long long)direction;
- (id)default;
- (id)operation;
@end

@protocol XDUMLProperty <XDUMLStructuralFeature, XDUMLTypedElement>
- (void)setIsReadOnly:(BOOL)arg1;
- (void)setIsComposite:(BOOL)arg1;
- (void)setAssociation:(id)arg1;
- (void)setDefaultValue:(id)arg1;
- (id)qualifier;
- (id)associationEnd;
- (unsigned long long)aggregation;
- (id)datatype;
- (id)subsettedProperties;
- (id)redefinedProperties;
- (id)owningAssociation;
- (id)association;
- (BOOL)isDerivedUnion;
- (id)opposite;
- (BOOL)isReadOnly;
- (BOOL)isDerived;
- (BOOL)isComposite;
- (id)defaultValue;
- (id)ownerClass;
@end

@protocol XDUMLRedefinableElement <XDUMLNamedElement>
- (BOOL)isLeaf;
- (id)redefinitionContext;
- (id)redefinedElement;
@end

@protocol XDUMLRelationship <XDUMLElement>
- (id)relatedElements;
@end

@protocol XDUMLStereotype <XDUMLClass>
@end

@protocol XDUMLStructuralFeature <XDUMLFeature, XDUMLTypedElement>
- (BOOL)isReadOnly;
@end

@protocol XDUMLType <XDUMLNamedElement>
- (id)package;
@end

@protocol XDUMLTypedElement <XDUMLNamedElement, XDUMLMultiplicityElement>
- (void)setType:(id)arg1;
- (id)type;
@end

@protocol XDUMLVisitor
- (void)visitImplementation:(id)arg1;
- (void)visitImplementations:(id)arg1;
- (void)visitGeneralization:(id)arg1;
- (void)visitGeneralizations:(id)arg1;
- (void)visitOperations:(id)arg1;
- (void)visitOperation:(id)arg1;
- (void)visitProperty:(id)arg1;
- (void)visitProperties:(id)arg1;
- (void)visitDataType:(id)arg1;
- (void)visitPackage:(id)arg1;
- (void)visitInterface:(id)arg1;
- (void)visitClass:(id)arg1;
- (void)visit:(id)arg1;
@end

@interface XDGenericErrorCallback : NSObject <XDErrorWarningCallback>
{
    NSDictionary *_compilerFlags;
    BOOL _success;
}

+ (id)stringForErrorCategory:(int)arg1;
- (BOOL)didSucceed;
- (BOOL)shouldContinue;
- (id)targetVersion;
- (id)compilerFlags;
- (id)descriptionForElement:(id)arg1;
- (void)createWarningForElement:(id)arg1 withFormat:(id)arg2 category:(int)arg3 documentURL:(id)arg4;
- (void)createWarningForElement:(id)arg1 withMessage:(id)arg2 category:(int)arg3 documentURL:(id)arg4;
- (void)createErrorForElement:(id)arg1 withFormat:(id)arg2 category:(int)arg3 documentURL:(id)arg4;
- (void)createErrorForElement:(id)arg1 withMessage:(id)arg2 category:(int)arg3 documentURL:(id)arg4;
- (void)dealloc;
- (id)initWithCompilerFlags:(id)arg1;

@end

@interface XDModel : NSObject <NSCoding>
{
    XDModelManager *_manager;
    NSString *_name;
    XDModelPackage *_rootPackage;
    NSMutableArray *_comments;
    id _controller;
}

- (id)newDataTypeWithName:(id)arg1 inPackage:(id)arg2;
- (id)newInterfaceWithName:(id)arg1 inPackage:(id)arg2;
- (id)newClassWithName:(id)arg1 inPackage:(id)arg2;
- (id)newComment;
- (id)newPackageWithName:(id)arg1;
- (id)newDataTypeWithName:(id)arg1;
- (id)newInterfaceWithName:(id)arg1;
- (id)newClassWithName:(id)arg1;
- (id)newAssociation;
- (id)newGeneralizationFrom:(id)arg1 to:(id)arg2;
- (id)newImplementationOf:(id)arg1 by:(id)arg2;
- (id)newStereotypeWithName:(id)arg1;
- (id)newParameterWithName:(id)arg1;
- (id)newOperationWithName:(id)arg1;
- (id)newPropertyWithName:(id)arg1;
- (void)removeObjectFromCommentsAtIndex:(unsigned long long)arg1;
- (void)insertObject:(id)arg1 inCommentsAtIndex:(unsigned long long)arg2;
- (id)comments;
- (id)controller;
- (void)setController:(id)arg1;
- (id)rootPackage;
- (void)setManager:(id)arg1;
- (id)manager;
- (void)setName:(id)arg1;
- (id)name;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)dealloc;
- (id)initWithName:(id)arg1;
- (id)_packagePathFromQualifiedName:(id)arg1;
- (id)_nameFromQualifiedName:(id)arg1;

@end

@interface XDModelPackage : XDUMLPackageImp
{
}

- (id)name;
- (id)qualifiedName;

@end

@interface XDPMAlias : XDPMProperty
{
}

- (void)setKeyPath:(id)arg1;
- (id)keyPath;
- (void)dealloc;
- (id)init;

@end

@interface XDPMAttribute : XDPMProperty
{
    NSDictionary *_attributeTypeDictionary;
}

+ (id)attributeTypeDictionaryForTypeString:(id)arg1;
+ (id)allAttributeTypeDictionaries;
+ (unsigned long long)attributeTypeForObjCTypeName:(id)arg1;
- (id)propertyDifferencesRelativeToProperty:(id)arg1 versionHashDiffsOnly:(BOOL)arg2;
- (id)versionHash;
- (id)code_propertyTypePointer;
- (void)generateErrorsAndWarningsWithCallback:(id)arg1 forDocumentAtURL:(id)arg2;
- (void)setAllowsExternalBinaryDataStorage:(BOOL)arg1;
- (BOOL)allowsExternalBinaryDataStorage;
- (id)possibleValuesForSharedKeyOne;
- (void)setSharedKeyOne:(id)arg1;
- (id)sharedKeyOne;
- (void)setValueTransformerName:(id)arg1;
- (id)valueTransformerName;
- (void)setRegularExpressionString:(id)arg1;
- (id)regularExpressionString;
- (BOOL)validateMaxValueString:(id *)arg1 error:(id *)arg2;
- (void)setMaxValueString:(id)arg1;
- (id)maxValueString;
- (BOOL)validateMinValueString:(id *)arg1 error:(id *)arg2;
- (void)setMinValueString:(id)arg1;
- (id)minValueString;
- (void)setDefaultValueForBooleanAsIndex:(long long)arg1;
- (long long)defaultValueForBooleanAsIndex;
- (BOOL)validateDefaultValueAsString:(id *)arg1 error:(id *)arg2;
- (void)setDefaultValueAsString:(id)arg1;
- (id)defaultValueAsString;
- (id)validateStringValue:(id)arg1 asType:(unsigned long long)arg2;
- (BOOL)_willHangNaturalLanguageParser:(id)arg1;
- (void)setDefaultValueObject:(id)arg1;
- (id)defaultValueObject;
- (id)_defaultValueObjectForString:(id)arg1 withType:(unsigned long long)arg2;
- (id)allAttributeTypeDictionaries;
- (void)setAttributeTypeDictionary:(id)arg1;
- (id)attributeTypeDictionary;
- (void)setAttributeTypeIndex:(long long)arg1;
- (long long)attributeTypeIndex;
- (void)_createAttributeTypesArray;
- (id)attributeTypeAsString;
- (void)setName:(id)arg1;
- (void)setAttributeType:(unsigned long long)arg1;
- (unsigned long long)attributeType;
- (id)propertyKind;
- (void)dealloc;
- (id)addKeysToDictionary:(id)arg1;
- (id)initWithDictionary:(id)arg1;
- (id)init;

@end

@interface XDPMAttributeScriptingWrapper : IDEScriptingWrapper
{
}

- (void)setUserInfo:(id)arg1;
- (id)userInfo;
- (void)setTransient:(BOOL)arg1;
- (BOOL)transient;
- (void)setOptional:(BOOL)arg1;
- (BOOL)optional;
- (id)name;
- (void)setDefaultValue:(id)arg1;
- (id)defaultValue;
- (void)setAttributeType:(id)arg1;
- (id)attributeType;

@end

@interface XDPMConfiguration : NSObject <NSCoding>
{
    NSString *_name;
    XDPMModel *_model;
    NSMutableArray *_entities;
}

+ (id)configurationFromPasteboradPlist:(id)arg1 model:(id)arg2;
- (id)pasteboardPlist;
- (id)undoManager;
- (BOOL)validateName:(id *)arg1 error:(id *)arg2;
- (void)removeAllEntities;
- (void)removeEntity:(id)arg1;
- (void)addEntity:(id)arg1;
- (id)_mutableEntities;
- (id)entities;
- (void)setModel:(id)arg1;
- (id)model;
- (void)setName:(id)arg1;
- (id)name;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)dealloc;
- (id)initWithName:(id)arg1;

@end

@interface XDPMEntity : XDUMLClassImp
{
    id <XDUMLGeneralization> _deletedInheritanceGeneralization;
    NSData *_versionHash;
}

+ (id)dictionaryOfPropertyPLists:(id)arg1;
+ (id)keyPathsForValuesAffectingSortedEntityRelationships;
+ (id)keyPathsForValuesAffectingSortedEntityFetchedProperties;
+ (id)keyPathsForValuesAffectingSortedEntityAttributes;
+ (id)sharedGenericRecordClass;
+ (id)syncUserInfoKeys;
+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;
- (id)propertyDifferencesRelativeToEntity:(id)arg1 versionHashDiffsOnly:(BOOL)arg2;
- (id)undoManager;
- (id)code_uniquedRelationshipDependencyNames;
- (id)code_relationshipDependencies;
- (id)code_hasAToManyRelationship;
- (id)code_hasParent;
- (id)code_entitySuperClass;
- (id)code_entityFileName;
- (void)generateErrorsAndWarningsWithCallback:(id)arg1 forDocumentAtURL:(id)arg2;
- (void)didChangeValueForKey:(id)arg1;
- (id)plistForDraggingtoIB;
- (BOOL)validateEntityClassName:(id *)arg1 error:(id *)arg2;
- (BOOL)validateName:(id *)arg1 error:(id *)arg2;
- (BOOL)_isInvalidEntityClassName:(id)arg1;
- (void)removeFromOwningConfigurations;
- (id)owningConfigurations;
- (void)setFetchRequests:(id)arg1;
- (void)removeObjectFromFetchRequests:(id)arg1;
- (void)addObjectToFetchRequests:(id)arg1;
- (void)_didChangeFetchRequests;
- (void)_willChangeFetchRequests;
- (id)fetchRequests;
- (id)newFetchRequestWithName:(id)arg1;
- (id)_mutableFetchRequests;
- (id)pastePropertiesWithDictionary:(id)arg1 entityNameMapTable:(id)arg2;
- (id)pasteFetchRequestsFromPlistArray:(id)arg1 entityNameMapTable:(id)arg2;
- (id)pasteRelationshipsFromPlistArray:(id)arg1 entityNameMapTable:(id)arg2;
- (id)newRelationshipWithName:(id)arg1 toDestination:(id)arg2 isToMany:(BOOL)arg3;
- (id)pasteFetchedPropertiesFromPlistArray:(id)arg1 entityNameMapTable:(id)arg2;
- (id)newFetchedPropertyWithName:(id)arg1;
- (id)newAttributeWithName:(id)arg1;
- (id)pasteAttributesFromPlistArray:(id)arg1 entityNameMapTable:(id)arg2;
- (id)allEntityRelationships;
- (id)allEntityFetchedProperties;
- (id)allEntityAttributes;
- (id)sortedEntityRelationships;
- (id)entityRelationships;
- (id)entityRelationshipsByName;
- (id)sortedEntityFetchedProperties;
- (id)entityFetchedPropertiesByName;
- (id)entityAttributesByName;
- (id)entityFetchedProperties;
- (id)sortedEntityAttributes;
- (id)sortedEntityProperties;
- (id)entityAttributes;
- (id)entityAliases;
- (id)entityPropertiesOfClassType:(Class)arg1;
- (void)removeEntityProperty:(id)arg1;
- (void)addEntityProperty:(id)arg1;
- (id)inheritedPropertyForName:(id)arg1;
- (id)entityPropertyForName:(id)arg1;
- (void)setEntityProperties:(id)arg1;
- (void)removeObjectFromEntityPropertiesAtIndex:(unsigned long long)arg1;
- (void)insertObject:(id)arg1 inEntityPropertiesAtIndex:(unsigned long long)arg2;
- (void)_didChangeProperties;
- (void)_willChangeProperties;
- (void)addObjectToEntityProperties:(id)arg1;
- (id)allEntityProperties;
- (id)entityProperties;
- (void)setUserInfo:(id)arg1;
- (id)userInfo;
- (void)setElementID:(id)arg1;
- (id)elementID;
- (void)setVersionHashModifier:(id)arg1;
- (id)versionHashModifier;
- (id)versionHash;
- (void)setEntityClassName:(id)arg1;
- (id)entityClassName;
- (id)deletedInheritanceGeneralization;
- (id)singleInheritanceGeneralization;
- (BOOL)isTreeLeaf;
- (id)inheritingEntities;
- (void)setInheritingEntities:(id)arg1;
- (BOOL)isChildOfEntity:(id)arg1;
- (id)possibleParentEntities;
- (void)setParentEntityName:(id)arg1;
- (void)setParentEntity:(id)arg1;
- (id)parentEntityName;
- (id)parentEntity;
- (void)setIsAbstract:(BOOL)arg1;
- (BOOL)isAbstract;
- (void)setUMLClassMapping:(id)arg1;
- (id)umlClassMapping;
- (id)model;
- (void)setName:(id)arg1;
- (void)fillInStateWithDictionary:(id)arg1 entityNameMapTable:(id)arg2;
- (id)addKeysToDictionary:(id)arg1;
- (void)dealloc;
- (id)init;

@end

@interface XDPMEntityScriptingWrapper : IDEScriptingWrapper
{
}

- (id)newScriptingObjectOfClass:(Class)arg1 forValueForKey:(id)arg2 withContentsValue:(id)arg3 properties:(id)arg4;
- (id)relationships;
- (id)fetchedProperties;
- (id)fetchRequests;
- (id)attributes;
- (void)setUserInfo:(id)arg1;
- (id)userInfo;
- (void)setParent:(id)arg1;
- (id)parent;
- (void)setObjectClass:(id)arg1;
- (id)objectClass;
- (id)name;
- (void)setAbstract:(BOOL)arg1;
- (BOOL)abstract;

@end

@interface XDPMFetchedProperty : XDPMProperty
{
}

- (void)generateErrorsAndWarningsWithCallback:(id)arg1 forDocumentAtURL:(id)arg2;
- (id)possibleDestinationEntities;
- (id)possibleValuesForSharedKeyOne;
- (void)setSharedKeyOne:(id)arg1;
- (id)sharedKeyOne;
- (BOOL)isEditableForTransientFlag;
- (BOOL)isEditableForOptionalFlag;
- (void)setIsOptional:(BOOL)arg1;
- (BOOL)isOptional;
- (void)setIsTransient:(BOOL)arg1;
- (BOOL)isTransient;
- (void)setFetchRequest:(id)arg1;
- (id)fetchRequest;
- (void)setName:(id)arg1;
- (id)propertyKind;
- (id)addKeysToDictionary:(id)arg1;
- (id)initWithDictionary:(id)arg1;
- (void)dealloc;
- (id)init;

@end

@interface XDPMFetchedPropertyScriptingWrapper : IDEScriptingWrapper
{
}

- (id)userInfo;
- (BOOL)transient;
- (id)predicate;
- (BOOL)optional;
- (id)name;
- (id)destination;

@end

@interface XDPMFetchRequest : NSObject <NSCoding>
{
    NSString *_name;
    XDPMEntity *_entity;
    NSString *_predicateString;
    XDPMFetchedProperty *_fetchedProperty;
    NSMutableDictionary *_initializationPendingKeys;
}

+ (id)fetchRequestFromPasteboardPlist:(id)arg1 model:(id)arg2;
- (id)undoManager;
- (BOOL)validateName:(id *)arg1 error:(id *)arg2;
- (void)didChangeValueForKey:(id)arg1;
- (void)setFetchBatchSize:(unsigned long long)arg1;
- (unsigned long long)fetchBatchSize;
- (void)setFetchOffset:(unsigned long long)arg1;
- (unsigned long long)fetchOffset;
- (void)setReturnsDistinctResults:(BOOL)arg1;
- (BOOL)returnsDistinctResults;
- (void)setIncludesPendingChanges:(BOOL)arg1;
- (BOOL)includesPendingChanges;
- (void)setReturnsObjectsAsFaults:(BOOL)arg1;
- (BOOL)returnsObjectsAsFaults;
- (void)setIncludesPropertyValues:(BOOL)arg1;
- (BOOL)includesPropertyValues;
- (void)setIncludesSubentities:(BOOL)arg1;
- (BOOL)includesSubentities;
- (void)setResultType:(unsigned long long)arg1;
- (unsigned long long)resultType;
- (void)setFetchLimit:(unsigned long long)arg1;
- (unsigned long long)fetchLimit;
- (void)setFetchedProperty:(id)arg1;
- (id)fetchedProperty;
- (void)setPredicateString:(id)arg1;
- (id)predicateString;
- (void)setEntity:(id)arg1;
- (id)entity;
- (void)setName:(id)arg1;
- (id)name;
- (id)undoTarget;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)addKeysToDictionary:(id)arg1;
- (id)initWithDictionary:(id)arg1;
- (void)dealloc;
- (id)initWithName:(id)arg1;

@end

@interface XDPMFetchRequestScriptingWrapper : IDEScriptingWrapper
{
}

- (id)name;
- (id)predicate;

@end

@interface XDPMModel : XDModel
{
    NSMutableDictionary *_fetchRequestsByName;
    NSMutableDictionary *_configurationsByName;
    BOOL _blockNotifications;
    NSUndoManager *_undoManager;
    id <XDPMModelDelegate> _delegate;
    NSString *_modelVersionIdentifier;
}

+ (id)arrayOfEntitiesPListsFromEntities:(id)arg1;
+ (id)keyPathsForValuesAffectingSortedEntities;
- (void)generateErrorsAndWarningsWithCallback:(id)arg1 forDocumentAtURL:(id)arg2;
- (void)setDelegate:(id)arg1;
- (id)delegate;
- (id)undoManager;
- (void)didChangeValueForKey:(id)arg1;
- (BOOL)blockNotifications;
- (void)setBlockNotifications:(BOOL)arg1;
- (void)setModelVersionIdentifier:(id)arg1;
- (id)modelVersionIdentifier;
- (void)removeConfiguration:(id)arg1;
- (void)addConfiguration:(id)arg1;
- (id)newConfigurationWithName:(id)arg1;
- (id)configurations;
- (id)configurationsByName;
- (void)removeFetchRequest:(id)arg1;
- (void)addFetchRequest:(id)arg1;
- (id)fetchRequests;
- (id)fetchRequestsByName;
- (id)entityForName:(id)arg1;
- (id)newEntityWithName:(id)arg1;
- (id)arrayOfFetchRequestsPlistsFromFetchRequests:(id)arg1;
- (void)fillInPastedEntitiesWithUpdatedPList:(id)arg1;
- (id)pasteEmptyEntitiesFromPList:(id)arg1;
- (id)elementsRelatedToEntity:(id)arg1;
- (void)removeEntity:(id)arg1;
- (void)addEntity:(id)arg1;
- (id)sortedEntities;
- (id)entities;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)dealloc;
- (id)initWithName:(id)arg1;

@end

@interface XDPMProperty : XDUMLPropertyImp
{
    NSMutableDictionary *_initializationPendingKeys;
    NSData *_versionHash;
}

+ (id)keyPathsForValuesAffectingIsStoredInTruthFile;
+ (id)keyPathsForValuesAffectingIsSpotlightIndexed;
- (id)propertyDifferencesRelativeToProperty:(id)arg1 versionHashDiffsOnly:(BOOL)arg2;
- (id)undoManager;
- (id)code_capitalizedPropertyName;
- (id)code_propertyName;
- (void)generateErrorsAndWarningsWithCallback:(id)arg1 forDocumentAtURL:(id)arg2;
- (void)didChangeValueForKey:(id)arg1;
- (BOOL)validateName:(id *)arg1 error:(id *)arg2;
- (id)possibleValuesForSharedKeyOne;
- (void)setSharedKeyOne:(id)arg1;
- (id)sharedKeyOne;
- (void)setElementID:(id)arg1;
- (id)elementID;
- (void)setIsStoredInTruthFile:(BOOL)arg1;
- (BOOL)isStoredInTruthFile;
- (void)setIsSpotlightIndexed:(BOOL)arg1;
- (BOOL)isSpotlightIndexed;
- (void)setVersionHashModifier:(id)arg1;
- (id)versionHashModifier;
- (id)versionHash;
- (void)setUserInfo:(id)arg1;
- (id)userInfo;
- (BOOL)isEditableForTransientFlag;
- (BOOL)isEditableForOptionalFlag;
- (void)setIsIndexed:(BOOL)arg1;
- (BOOL)isIndexed;
- (void)setIsTransient:(BOOL)arg1;
- (BOOL)isTransient;
- (void)setIsOptional:(BOOL)arg1;
- (BOOL)isOptional;
- (id)entity;
- (id)propertyKind;
- (void)setName:(id)arg1;
- (void)dealloc;
- (id)initializationPendingKeys;
- (id)addKeysToDictionary:(id)arg1;
- (id)initWithDictionary:(id)arg1;
- (id)init;

@end

@interface XDPMRelationship : XDPMProperty
{
    NSDictionary *_deleteRuleDictionary;
}

+ (unsigned long long)deleteRuleValueForString:(id)arg1;
+ (id)allDeleteRuleDictionaries;
+ (id)deleteRuleDictionaryForValue:(unsigned long long)arg1;
+ (id)deleteRuleStringForValue:(unsigned long long)arg1;
- (id)propertyDifferencesRelativeToProperty:(id)arg1 versionHashDiffsOnly:(BOOL)arg2;
- (id)versionHash;
- (id)code_relationshipDestinationClass;
- (id)code_relationshipSetType;
- (void)generateErrorsAndWarningsWithCallback:(id)arg1 forDocumentAtURL:(id)arg2;
- (id)possibleValuesForSharedKeyOne;
- (void)setSharedKeyOne:(id)arg1;
- (id)sharedKeyOne;
- (id)possibleInverseRelationships;
- (id)possibleDestinationEntities;
- (id)allDeleteRuleDictionaries;
- (void)setIsOptional:(BOOL)arg1;
- (void)setIsToMany:(BOOL)arg1;
- (BOOL)isToMany;
- (BOOL)isIndexed;
- (void)setInverseRelationship:(id)arg1;
- (id)inverseRelationship;
- (void)setDeleteRuleDictionary:(id)arg1;
- (id)deleteRuleDictionary;
- (id)deleteRuleAsString;
- (void)setDeleteRule:(unsigned long long)arg1;
- (unsigned long long)deleteRule;
- (void)setOrdered:(BOOL)arg1;
- (BOOL)ordered;
- (void)setMaxCountNumber:(id)arg1;
- (id)maxCountNumber;
- (void)setMinCountNumber:(id)arg1;
- (id)minCountNumber;
- (void)setMaxCount:(long long)arg1;
- (long long)maxCount;
- (void)setMinCount:(long long)arg1;
- (long long)minCount;
- (void)setDestinationEntity:(id)arg1;
- (id)destinationEntity;
- (id)propertyKind;
- (void)dealloc;
- (id)addKeysToDictionary:(id)arg1;
- (void)setName:(id)arg1;
- (id)initWithDictionary:(id)arg1;
- (id)init;

@end

@interface XDPMRelationshipScriptingWrapper : IDEScriptingWrapper
{
}

- (id)userInfo;
- (BOOL)transient;
- (BOOL)toMany;
- (BOOL)optional;
- (id)name;
- (long long)minimumCount;
- (long long)maximumCount;
- (id)inverseRelationship;
- (id)destinationEntity;

@end

@interface XDProject : NSObject
{
    NSString *_name;
    NSMutableDictionary *_modelManagers;
}

+ (id)sharedManagerForOfType:(id)arg1 inKey:(id)arg2;
+ (void)registerModelManagerClass:(Class)arg1;
+ (id)sharedXDProjectForKey:(id)arg1;
- (id)modelManagers;
- (id)modelManagerForName:(id)arg1;
- (void)removeModelManager:(id)arg1;
- (void)addModelManager:(id)arg1;
- (void)setName:(id)arg1;
- (id)name;
- (void)encodeWithCoder:(id)arg1;
- (void)dealloc;
- (id)init;

@end

@interface XDPUtility : NSObject
{
}

+ (id)validateElementName:(id)arg1 beginWithLowerCase:(BOOL)arg2 beginWithUpperCase:(BOOL)arg3 allowPeriod:(BOOL)arg4;
+ (void)_makeNameValidationSets;
+ (BOOL)booleanForKey:(id)arg1 inElement:(id)arg2 inStereotypeName:(id)arg3;
+ (void)setBoolean:(BOOL)arg1 forKey:(id)arg2 inElement:(id)arg3 inStereotypeName:(id)arg4;
+ (id)objectForKey:(id)arg1 inElement:(id)arg2 inStereotypeName:(id)arg3;
+ (void)setObject:(id)arg1 forKey:(id)arg2 inElement:(id)arg3 inStereotypeName:(id)arg4;
+ (void)removeStereotypeNamed:(id)arg1 inElement:(id)arg2;

@end

@interface XDUMLAbstractionImp : XDUMLNamedElementImp <XDUMLAbstraction>
{
    NSMutableArray *_targets;
    NSMutableArray *_sources;
}

- (unsigned long long)visibility;
- (id)relatedElements;
- (void)addClient:(id)arg1;
- (void)addSupplier:(id)arg1;
- (id)clients;
- (id)suppliers;
- (id)sources;
- (id)targets;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)dealloc;
- (id)init;

@end

@interface XDUMLAssociationImpl : XDUMLClassifierImp <XDUMLAssociation>
{
    NSMutableArray *_ends;
}

- (void)addMemberEnd:(id)arg1;
- (id)relatedElements;
- (id)memberEnds;
- (id)ownedEnds;
- (BOOL)isDerived;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)dealloc;
- (id)init;

@end

@interface XDUMLClassifierImp : XDUMLNamespaceImp <XDUMLClassifier>
{
    BOOL _isAbstract;
}

- (id)newOperationWithName:(id)arg1;
- (id)operationForName:(id)arg1;
- (void)removeOperation:(id)arg1;
- (void)addOperation:(id)arg1;
- (id)newPropertyWithName:(id)arg1;
- (id)propertyForName:(id)arg1;
- (void)removeProperty:(id)arg1;
- (void)addProperty:(id)arg1;
- (void)removeObjectFromPropertiesAtIndex:(unsigned long long)arg1;
- (void)insertObject:(id)arg1 inPropertiesAtIndex:(unsigned long long)arg2;
- (id)properties;
- (id)ownedOperations;
- (id)ownedAttributes;
- (BOOL)lazyCreateBucketNamed:(id)arg1;
- (void)specializationRemoved:(id)arg1;
- (void)specializationAdded:(id)arg1;
- (id)specializations;
- (id)newGeneralizationFrom:(id)arg1;
- (void)generalizationRemoved:(id)arg1;
- (void)generalizationAdded:(id)arg1;
- (id)package;
- (void)setIsAbstract:(BOOL)arg1;
- (id)attributes;
- (BOOL)isAbstract;
- (id)generalizations;
- (id)features;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)dealloc;
- (id)init;

@end

@interface XDUMLClassImp : XDUMLClassifierImp <XDUMLClass>
{
}

- (void)setParentClass:(id)arg1;
- (id)parentClass;
- (BOOL)lazyCreateBucketNamed:(id)arg1;
- (id)description;
- (id)newImplementationOf:(id)arg1;
- (void)implementationRemoved:(id)arg1;
- (void)implementationAdded:(id)arg1;
- (id)superClasses;
- (id)ownedOperations;
- (id)ownedAttributes;
- (id)implementations;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)dealloc;

@end

@interface XDUMLCommentImp : XDUMLElementImp <XDUMLComment>
{
    NSString *_body;
}

- (id)name;
- (void)removeObjectFromAnnotatedElementsAtIndex:(unsigned long long)arg1;
- (void)insertObject:(id)arg1 inAnnotatedElementsAtIndex:(unsigned long long)arg2;
- (void)setBody:(id)arg1;
- (BOOL)lazyCreateBucketNamed:(id)arg1;
- (id)annotatedElements;
- (id)body;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)dealloc;
- (id)init;

@end

@interface XDUMLDataTypeImp : XDUMLClassifierImp <XDUMLDataType>
{
}

- (id)description;
- (id)ownedOperations;
- (id)ownedAttributes;

@end

@interface XDUMLDefaultVisitor : NSObject <XDUMLVisitor>
{
}

- (void)visitImplementation:(id)arg1;
- (void)visitImplementations:(id)arg1;
- (void)visitGeneralization:(id)arg1;
- (void)visitGeneralizations:(id)arg1;
- (void)visitOperation:(id)arg1;
- (void)visitOperations:(id)arg1;
- (void)visitProperty:(id)arg1;
- (void)visitProperties:(id)arg1;
- (void)visitDataType:(id)arg1;
- (void)visitInterface:(id)arg1;
- (void)visitClass:(id)arg1;
- (void)visitPackage:(id)arg1;
- (void)visit:(id)arg1;
- (void)visitSelection:(id)arg1;

@end

@interface XDWeakReference : NSObject
{
    id _objReference;
}

+ (id)weakRefWithObj:(id)arg1;
- (BOOL)isEqual:(id)arg1;
- (id)objectReference;
- (id)initWithObjectReference:(id)arg1;

@end

@interface XDUMLElementImp : NSObject <XDUMLElement, NSCoding>
{
    NSMutableDictionary *_elementsByBucket;
    id _uniqueElementID;
    id <XDUMLElement> _owner;
}

- (id)elementsInAllBuckets;
- (id)elementsInBucketNamed:(id)arg1;
- (unsigned long long)elementsCountInBucketNamed:(id)arg1;
- (void)removeElementAtIndex:(unsigned long long)arg1 fromBucketNamed:(id)arg2;
- (void)removeElement:(id)arg1 fromBucketNamed:(id)arg2;
- (unsigned long long)indexForElement:(id)arg1 inBucketNamed:(id)arg2;
- (id)elementForName:(id)arg1 inBucketNamed:(id)arg2;
- (void)addElement:(id)arg1 toBucketNamed:(id)arg2 atIndex:(unsigned long long)arg3;
- (BOOL)lazyCreateBucketNamed:(id)arg1;
- (void)deleteElementsBucketWithName:(id)arg1;
- (void)createElementsBucketWithName:(id)arg1 allowsDuplicates:(BOOL)arg2 preserveInsertOrder:(BOOL)arg3;
- (void)decodeBucketName:(id)arg1 withCoder:(id)arg2;
- (void)encodeBucketName:(id)arg1 withCoder:(id)arg2;
- (void)namedElement:(id)arg1 inBucket:(id)arg2 wasRenamedFrom:(id)arg3 to:(id)arg4;
- (void)_convertBucketStorage:(id)arg1;
- (BOOL)shouldEncodeBucketNamed:(id)arg1;
- (id)newStereotypeWithName:(id)arg1;
- (void)removeStereotype:(id)arg1;
- (void)addStereotype:(id)arg1;
- (id)stereotypes;
- (void)removeObjectFromOwnedCommentsAtIndex:(unsigned long long)arg1;
- (void)insertObject:(id)arg1 inOwnedCommentsAtIndex:(unsigned long long)arg2;
- (id)ownedComments;
- (void)setOwner:(id)arg1;
- (id)owner;
- (id)ownedElements;
- (void)setUniqueElementID:(id)arg1;
- (id)createUniqueElementID;
- (id)uniqueElementID;
- (id)bucketContainer;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)dealloc;
- (id)init;

@end

@interface XDUMLEnumerationImp : XDUMLDataTypeImp <XDUMLEnumeration>
{
    NSMutableArray *_literals;
}

- (id)newLiteralWithName:(id)arg1;
- (id)ownedLiterals;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)dealloc;
- (id)init;

@end

@interface XDUMLEnumerationLiteralImp : XDUMLNamedElementImp
{
}

- (id)description;
- (id)enumeration;

@end

@interface XDUMLGeneralizationImp : XDUMLNamedElementImp <XDUMLGeneralization>
{
    id <XDUMLClassifier> _general;
    id <XDUMLClassifier> _specific;
}

- (id)description;
- (void)setSpecific:(id)arg1;
- (void)setGeneral:(id)arg1;
- (void)remove;
- (id)specific;
- (id)general;
- (id)relatedElements;
- (id)sources;
- (id)targets;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)dealloc;
- (id)init;

@end

@interface XDUMLHelper : NSObject
{
}

+ (id)uniqueStringValue:(id)arg1 inObjectArray:(id)arg2 objectKey:(id)arg3;
+ (id)uniqueStringValue:(id)arg1 inStringArray:(id)arg2;
+ (id)findElementNamed:(id)arg1 inArray:(id)arg2;
+ (id)findElementNamed:(id)arg1 inArray:(id)arg2 forSelector:(SEL)arg3;

@end

@interface XDUMLImplementationImp : XDUMLClassifierImp <XDUMLImplementation>
{
    id <XDUMLInterface> _contract;
}

- (id)description;
- (void)setContract:(id)arg1;
- (void)setOwner:(id)arg1;
- (void)remove;
- (id)implementingClassifier;
- (id)contract;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)dealloc;

@end

@interface XDUMLInterfaceImp : XDUMLClassifierImp <XDUMLInterface>
{
}

- (BOOL)lazyCreateBucketNamed:(id)arg1;
- (id)description;
- (void)implementorRemoved:(id)arg1;
- (void)implementorAdded:(id)arg1;
- (id)implementors;
- (id)redefinedInterface;
- (id)nestedInterface;
- (id)ownedOperations;
- (id)ownedAttributes;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)dealloc;
- (id)init;

@end

@interface XDUMLNamedElementImp : XDUMLElementImp <XDUMLNamedElement>
{
    NSString *_name;
    unsigned long long _visibility;
    NSMutableArray *_containingBuckets;
}

- (id)description;
- (void)removeContainingBucket:(id)arg1;
- (void)addContainingBucket:(id)arg1;
- (id)separator;
- (void)setVisibility:(unsigned long long)arg1;
- (unsigned long long)visibility;
- (id)namespace;
- (id)qualifiedName;
- (void)setName:(id)arg1;
- (id)name;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)dealloc;
- (id)init;

@end

@interface XDUMLNamespaceImp : XDUMLNamedElementImp <XDUMLNamespace>
{
}

- (id)ownedMembers;
- (id)members;

@end

@interface XDUMLOperationImp : XDUMLNamespaceImp <XDUMLOperation>
{
    BOOL _isStatic;
    BOOL _isLeaf;
    BOOL _isQuery;
    NSMutableArray *_parameters;
    NSMutableArray *_returnResults;
}

- (id)description;
- (void)setOwnedParameters:(id)arg1;
- (void)setIsLeaf:(BOOL)arg1;
- (void)setIsQuery:(BOOL)arg1;
- (id)newReturnParameterWithType:(id)arg1;
- (id)newParameterWithName:(id)arg1;
- (BOOL)isLeaf;
- (id)redefinitionContext;
- (id)redefinedElement;
- (id)ownedMembers;
- (id)members;
- (void)setIsStatic:(BOOL)arg1;
- (BOOL)isStatic;
- (id)featuringClassifiers;
- (id)returnResult;
- (id)formalParameters;
- (id)parameters;
- (id)type;
- (id)redefinedOperations;
- (long long)upper;
- (long long)lower;
- (BOOL)isUnique;
- (BOOL)isQuery;
- (BOOL)isOrdered;
- (id)raisedExceptions;
- (id)ownedParameters;
- (id)ownerClass;
- (BOOL)lazyCreateBucketNamed:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)dealloc;
- (id)init;

@end

@interface XDUMLPackageImp : XDUMLNamespaceImp <XDUMLPackage>
{
    XDModel *_model;
}

- (id)description;
- (void)setModel:(id)arg1;
- (id)model;
- (id)packageForName:(id)arg1;
- (void)removePackage:(id)arg1;
- (void)addPackage:(id)arg1 toQualifierPath:(id)arg2;
- (id)dataTypeForName:(id)arg1;
- (void)addDataType:(id)arg1 toQualifierPath:(id)arg2;
- (id)allInterfaces;
- (id)interfaceForName:(id)arg1;
- (void)removeInterface:(id)arg1;
- (void)addInterface:(id)arg1 toQualifierPath:(id)arg2;
- (id)allClasses;
- (id)classForName:(id)arg1;
- (void)removeClass:(id)arg1;
- (void)addClass:(id)arg1 toQualifierPath:(id)arg2;
- (void)addElement:(id)arg1 toQualifierPath:(id)arg2 withBucketNamed:(id)arg3;
- (id)packageAtQualifierPath:(id)arg1 forceCreation:(BOOL)arg2;
- (BOOL)lazyCreateBucketNamed:(id)arg1;
- (void)addType:(id)arg1;
- (id)nestingPackage;
- (id)nestedPackages;
- (id)ownedTypes;
- (id)ownedMembers;
- (void)deleteElementsBucketWithName:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)dealloc;
- (id)initWithModel:(id)arg1;

@end

@interface XDUMLParameterImp : XDUMLNamedElementImp <XDUMLParameter>
{
    unsigned long long _direction;
    BOOL _isOrdered;
    BOOL _isUnique;
    NSString *_default;
    id <XDUMLType> _type;
}

- (id)description;
- (long long)upper;
- (long long)lower;
- (BOOL)isUnique;
- (BOOL)isOrdered;
- (void)setType:(id)arg1;
- (id)type;
- (void)setDirection:(unsigned long long)arg1;
- (unsigned long long)direction;
- (id)default;
- (id)operation;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)dealloc;
- (id)init;

@end

@interface XDUMLPropertyImp : XDUMLNamedElementImp <XDUMLProperty>
{
    BOOL _isStatic;
    BOOL _isLeaf;
    BOOL _isOrdered;
    BOOL _isUnique;
    BOOL _isReadOnly;
    BOOL _isDerived;
    BOOL _isComposite;
    id <XDUMLType> _type;
    NSString *_default;
    id <XDUMLAssociation> _association;
}

- (id)description;
- (void)setIsReadOnly:(BOOL)arg1;
- (void)setIsComposite:(BOOL)arg1;
- (void)setAssociation:(id)arg1;
- (void)setType:(id)arg1;
- (id)type;
- (BOOL)isLeaf;
- (id)redefinitionContext;
- (id)redefinedElement;
- (id)qualifier;
- (id)associationEnd;
- (unsigned long long)aggregation;
- (id)datatype;
- (id)subsettedProperties;
- (id)redefinedProperties;
- (id)owningAssociation;
- (id)association;
- (BOOL)isDerivedUnion;
- (id)opposite;
- (BOOL)isReadOnly;
- (BOOL)isDerived;
- (BOOL)isComposite;
- (void)setDefaultValue:(id)arg1;
- (id)defaultValue;
- (id)ownerClass;
- (long long)upper;
- (long long)lower;
- (BOOL)isUnique;
- (BOOL)isOrdered;
- (void)setIsStatic:(BOOL)arg1;
- (BOOL)isStatic;
- (id)featuringClassifiers;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)dealloc;

@end

@interface XDUMLStereotypeImp : XDUMLClassImp <XDUMLStereotype>
{
}

@end

@interface XDPMConfigurationSetting : NSObject
{
    XDPMConfiguration *_configuration;
    NSArray *_entities;
    long long _chosen;
}

- (BOOL)validateName:(id *)arg1 error:(id *)arg2;
- (void)finalize;
- (void)dealloc;
- (void)_removeObservers;
- (id)configuration;
- (void)setConfiguration:(id)arg1;
- (void)_removeConfigurationObservers;
- (long long)chosen;
- (void)setChosen:(long long)arg1;
- (void)setInitiallyChosen:(long long)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (id)entities;
- (void)setEntities:(id)arg1;
- (void)computeChosen;
- (id)name;
- (void)setName:(id)arg1;

@end

@interface XDTemplateExpander : NSObject
{
    NSMutableDictionary *_settingsDict;
    NSMutableString *_templateString;
    NSMutableArray *_errorArray;
    BOOL _isInLoop;
    BOOL _isInIF;
    BOOL _isInNotIF;
    BOOL _continueGeneration;
}

+ (id)expandTemplateString:(id)arg1 withSetting:(id)arg2 errorsArray:(id)arg3;
- (id)expandLoopString:(id)arg1;
- (id)expandConditionalString:(id)arg1 negate:(BOOL)arg2;
- (id)substituteReference:(id)arg1;
- (id)expandString:(id)arg1;
- (id)expandedResult;
- (void)dealloc;
- (id)initWithTemplateString:(id)arg1 settings:(id)arg2 errorsArray:(id)arg3;

@end

@interface XDPMCodeGenerationController : NSObject
{
}

+ (id)generateImplementationsWithOptions:(id)arg1;
+ (id)generateDeclarationsWithOptions:(id)arg1;
+ (id)_generateCodeSnippetFromFileName:(id)arg1 withOptions:(id)arg2;
+ (id)availableTemplatesForCodeGeneration;
+ (void)clearCaches;
+ (id)templateStringForDefinitionName:(id)arg1 fileName:(id)arg2;
+ (id)templateDefinitionsByName;

@end

@interface XDDevAttributeMapping : XDDevPropertyMapping
{
}

+ (void)initialize;
- (id)possibleNames;
- (id)valueExpressionAsString;
- (id)shortPropertyType;
- (Class)propertyClassType;

@end

@interface XDDevMappingModel : NSManagedObject <CDMIdentification>
{
    NSArray *_defaultEntityMappingTypeNames;
    IDEMappingModelDocument *document;
    NSNumber *uniqueID;
    NSString *name;
}

+ (id)keyPathsForValuesAffectingSortedEntityMappings;
@property(copy) NSNumber *uniqueID; // @synthesize uniqueID;
@property(copy) NSString *name; // @synthesize name;
@property IDEMappingModelDocument *document; // @synthesize document;
- (void)moveEntityMappings:(id)arg1 toPosition:(long long)arg2;
- (BOOL)renumberEntityMappings;
- (void)generateErrorsAndWarningsWithCallback:(id)arg1;
- (void)updateDestinationModelWithModel:(id)arg1;
- (void)updateSourceModelWithModel:(id)arg1;
- (void)generateDefaultMappings;
- (id)sortedEntityMappingsByName;
- (id)sortedEntityMappings;
- (id)defaultEntityMappingUIStrings;
- (void)removeEntityMappingsObject:(id)arg1;
- (void)addEntityMappingsObject:(id)arg1;
- (id)errorIcon;
- (void)setDestinationModelPath:(id)arg1;
- (id)destinationModelPath;
- (void)setSourceModelData:(id)arg1;
- (id)sourceModelData;
- (void)setSourceModelPath:(id)arg1;
- (id)sourceModelPath;
- (void)setDestinationModelData:(id)arg1;
- (id)destinationModelData;
- (void)setSourceModel:(id)arg1;
- (id)sourceModel;
- (void)setDestinationModel:(id)arg1;
- (id)destinationModel;
- (void)dealloc;

@end

@interface XDDevPropertyMapping : NSManagedObject <CDMIdentification>
{
    BOOL _isObservingSourceName;
    IDEMappingModelDocument *document;
    NSNumber *uniqueID;
}

+ (id)keyPathsForValuesAffectingUserInfoDictionary;
+ (void)setPropertyMappingTriggerNotifications;
+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;
@property(copy) NSNumber *uniqueID; // @synthesize uniqueID;
@property IDEMappingModelDocument *document; // @synthesize document;
- (BOOL)hasDuplicateName;
- (BOOL)isInDestinationEntity;
- (BOOL)hasValidName;
- (id)mappingStatusIcon;
- (id)possibleNames;
- (void)generateErrorsAndWarningsWithCallback:(id)arg1;
- (BOOL)validateValueExpressionAsString:(id *)arg1 error:(id *)arg2;
- (void)setValueExpressionAsString:(id)arg1;
- (id)valueExpressionAsString;
- (void)setEntityMapping:(id)arg1;
- (id)entityMapping;
- (id)shortPropertyType;
- (Class)propertyClassType;
- (void)setUserInfo:(id)arg1;
@property(copy) NSDictionary *userInfoDictionary;
- (id)userInfo;
- (void)setUserInfoData:(id)arg1;
- (id)userInfoData;
- (void)setValueExpressionData:(id)arg1;
- (id)valueExpressionData;
@property(copy) NSString *name;
- (void)setValueExpression:(id)arg1;
- (id)valueExpression;

@end

@interface XDMappingModelManager : NSObject
{
    NSString *_modelFilePath;
    NSPersistentStoreCoordinator *_persistentStoreCoordinator;
    NSManagedObjectModel *_managedObjectModel;
    NSManagedObjectContext *_managedObjectContext;
    XDDevMappingModel *_mappingModelInstance;
    NSUndoManager *_undoManager;
    NSPersistentStore *_store;
}

- (id)newModelObjectOfClass:(Class)arg1;
@property(readonly) NSString *modelFilePath;
- (id)mappingModelInstance;
- (id)managedObjectContext;
- (id)managedObjectModel;
- (BOOL)saveContextToPath:(id)arg1 error:(id *)arg2;
- (id)persistentStoreCoordinator;
- (void)dealloc;
- (id)initWithFilePath:(id)arg1 undoManager:(id)arg2;
- (id)storeURLWithModelPath:(id)arg1;

@end

@interface XDMappingCompilerSupport : NSObject <XDMappingCompilerCallback>
{
    XDMappingModelManager *_modelManager;
    NSMutableArray *_errorsAndWarnings;
    id _result;
    BOOL _hasErrors;
    NSDictionary *_options;
}

+ (id)stringForErrorCategory:(int)arg1;
- (id)targetVersion;
- (BOOL)continueGeneration;
- (void)addWarningForElement:(id)arg1 prefix:(id)arg2 message:(id)arg3 category:(int)arg4;
- (void)addErrorForElement:(id)arg1 prefix:(id)arg2 message:(id)arg3 category:(int)arg4;
- (void)printCompiledObject:(id)arg1;
- (id)printErrorsAndWarnings:(BOOL)arg1;
- (BOOL)hasErrors;
- (id)errorsAndWarnings;
- (id)result;
- (BOOL)compileSourcePath:(id)arg1 options:(id)arg2;
- (void)generateCompileResultForMappingModel:(id)arg1;
- (void)dealloc;
- (id)init;

@end

@interface XDDevRelationshipMapping : XDDevPropertyMapping
{
}

+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;
+ (void)initialize;
- (id)possibleNames;
- (void)generateErrorsAndWarningsWithCallback:(id)arg1;
- (BOOL)destinationHasChildren;
- (id)valueExpressionAsString;
- (void)setSourceMappingName:(id)arg1;
- (id)possibleSourceExpressions;
- (id)sourceMappingName;
- (void)setSourceKeyPath:(id)arg1;
- (id)sourceKeyPath;
- (id)shortPropertyType;
- (Class)propertyClassType;
- (void)setAutoGenerateExpression:(id)arg1;
- (id)autoGenerateExpression;

@end

@interface XDMappingModelUtilities : NSObject
{
}

@end

@interface XDDevEntityMapping : NSManagedObject <CDMIdentification>
{
    IDEMappingModelDocument *document;
    NSNumber *uniqueID;
}

+ (id)entityMappingStringFromType:(unsigned long long)arg1;
+ (unsigned long long)entityMappingTypeFromUIString:(id)arg1;
+ (id)defaultEntityMappingUIStrings;
+ (id)keyPathsForValuesAffectingSortedRelationshipMappings;
+ (id)keyPathsForValuesAffectingSortedAttributeMappings;
+ (id)keyPathsForValuesAffectingUserInfoDictionary;
+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;
@property(copy) NSNumber *uniqueID; // @synthesize uniqueID;
@property IDEMappingModelDocument *document; // @synthesize document;
- (void)generateErrorsAndWarningsWithCallback:(id)arg1;
- (void)addMissingPropertyMappings;
- (id)sortedRelationshipMappings;
- (id)sortedAttributeMappings;
- (id)sortedPropertyMappings;
- (id)destinationEntity;
- (id)sourceEntity;
- (BOOL)hasValidDestinationName;
- (BOOL)hasValidSourceName;
- (id)mappingStatusIcon;
- (id)mappingTypeIcon;
- (id)_mappingTypeIconsByMappingName;
- (void)addPropertyMappingsObject:(id)arg1;
- (void)removeRelationshipMappingsObject:(id)arg1;
- (void)addRelationshipMappingsObject:(id)arg1;
- (void)removeAttributeMappingsObject:(id)arg1;
- (void)addAttributeMappingsObject:(id)arg1;
- (void)setMappingModel:(id)arg1;
- (id)mappingModel;
- (BOOL)validateSourceExpressionAsString:(id *)arg1 error:(id *)arg2;
- (void)setSourceExpressionAsString:(id)arg1;
- (id)sourceExpressionAsString;
- (void)setSourceExpression:(id)arg1;
- (id)sourceExpression;
@property(copy) NSString *name;
- (id)hasHashDifferencesShortString;
- (id)shortMappingTypeName;
- (void)setMappingTypeName:(id)arg1;
- (id)mappingTypeName;
- (void)setMigrationPolicyClassName:(id)arg1;
- (id)migrationPolicyClassName;
- (BOOL)validateSourceFilterPredicateString:(id *)arg1 error:(id *)arg2;
- (void)setSourceFilterPredicateString:(id)arg1;
- (id)sourceFilterPredicateString;
- (void)setSourceExpressionData:(id)arg1;
- (id)sourceExpressionData;
- (void)setUserInfoData:(id)arg1;
- (id)userInfoData;
- (void)setMappingNumber:(id)arg1;
- (id)mappingNumber;
@property(copy) NSDictionary *userInfoDictionary;
- (void)setUserInfo:(id)arg1;
- (id)userInfo;
- (void)setDestinationName:(id)arg1;
- (id)destinationName;
- (void)setSourceName:(id)arg1;
- (id)sourceName;
- (void)setAutoGenerateExpression:(id)arg1;
- (id)autoGenerateExpression;

@end

@interface CDMProperty : NSObject <IDEInspectorAccessibilitySupport, CDMIdentification>
{
    NSString *name;
    BOOL optional;
    BOOL optionalFlagEnabled;
    BOOL transient;
    BOOL transientFlagEnabled;
    BOOL indexed;
    NSString *elementID;
    BOOL spotlightIndexingEnabled;
    BOOL storedInTruthFile;
    NSMutableDictionary *userInfoDictionary;
    id sharedKey;
    NSString *versionHashModifier;
    CDMModel *model;
    CDMEntity *entity;
    NSNumber *uniqueID;
    BOOL syncable;
    BOOL isSyncIdentityProperty;
    BOOL excludeFromDataChangeAlert;
    unsigned long long preferredClientType;
    unsigned long long preferredRecord;
}

+ (id)keyPathsForValuesAffectingInspectedOptional;
+ (id)keyPathsForValuesAffectingInspectedSyncable;
@property unsigned long long preferredRecord; // @synthesize preferredRecord;
@property unsigned long long preferredClientType; // @synthesize preferredClientType;
@property BOOL excludeFromDataChangeAlert; // @synthesize excludeFromDataChangeAlert;
@property BOOL isSyncIdentityProperty; // @synthesize isSyncIdentityProperty;
@property BOOL syncable; // @synthesize syncable;
@property(copy) NSNumber *uniqueID; // @synthesize uniqueID;
@property(copy) NSString *versionHashModifier; // @synthesize versionHashModifier;
@property(copy) NSString *name; // @synthesize name;
@property BOOL transient; // @synthesize transient;
@property BOOL optional; // @synthesize optional;
@property CDMEntity *entity; // @synthesize entity;
@property CDMModel *model; // @synthesize model;
@property id sharedKey; // @synthesize sharedKey;
@property(copy) NSDictionary *userInfoDictionary; // @synthesize userInfoDictionary;
@property BOOL storedInTruthFile; // @synthesize storedInTruthFile;
@property BOOL spotlightIndexingEnabled; // @synthesize spotlightIndexingEnabled;
@property(copy) NSString *elementID; // @synthesize elementID;
@property BOOL indexed; // @synthesize indexed;
@property(readonly) BOOL transientFlagEnabled; // @synthesize transientFlagEnabled;
@property(readonly) BOOL optionalFlagEnabled; // @synthesize optionalFlagEnabled;
- (id)stringRepresentation;
- (id)userInfoXMLElementTree;
- (id)xmlElementAttributesByType;
- (id)secondaryXMLElementAttributes;
- (id)primaryXMLElementAttributes;
- (id)initWithXMLElementDescription:(id)arg1 belongingToModel:(id)arg2;
- (id)navigableItem_name;
- (id)addKeysToDictionary:(id)arg1;
- (id)initWithDictionary:(id)arg1;
- (void)generateErrorsAndWarningsWithCallback:(id)arg1 forDocumentAtURL:(id)arg2;
- (id)undoManager;
@property(readonly) NSData *versionHash;
- (void)cascadeChangesToLegacyProperty:(id)arg1;
- (id)initWithLegacyProperty:(id)arg1 belongingToEntity:(id)arg2 inModel:(id)arg3;
- (void)updateSyncingSupportForEntity:(id)arg1;
- (id)init;
- (void)commonInit;
- (void)setPreferredRecordString:(id)arg1;
@property(readonly) NSString *preferredRecordString;
- (void)setPreferredClientTypeString:(id)arg1;
@property(readonly) NSString *preferredClientTypeString;
- (void)setInspectedOptional:(BOOL)arg1;
- (BOOL)inspectedOptional;
- (void)didChangeValueForKey:(id)arg1;
- (void)setInspectedSyncable:(BOOL)arg1;
- (BOOL)inspectedSyncable;
- (id)humanReadableNameForInspectorKeyPath:(id)arg1;
- (id)code_capitalizedPropertyName;
- (id)code_propertyName;
- (BOOL)validateName:(id *)arg1 error:(id *)arg2;

@end

@interface CDMAttribute : CDMProperty
{
    long long attributeType;
    NSString *defaultValueString;
    NSString *minValueString;
    NSString *maxValueString;
    NSString *regularExpressionString;
    NSString *valueTransformerName;
    NSMutableArray *attributeTypes;
    BOOL allowsExternalBinaryDataStorage;
}

+ (id)keyPathsForValuesAffectingInspectedAttributeType;
+ (id)keyPathsForValuesAffectingMaxValueObject;
+ (id)keyPathsForValuesAffectingMaxValueString;
+ (id)keyPathsForValuesAffectingMinValueObject;
+ (id)keyPathsForValuesAffectingMinValueString;
@property long long attributeType; // @synthesize attributeType;
@property(copy) NSString *valueTransformerName; // @synthesize valueTransformerName;
@property(copy) NSString *regularExpressionString; // @synthesize regularExpressionString;
@property(copy) NSString *maxValueString; // @synthesize maxValueString;
@property(copy) NSString *minValueString; // @synthesize minValueString;
@property(copy) NSString *defaultValueString; // @synthesize defaultValueString;
- (id)stringRepresentation;
- (id)xmlElementDescription;
- (id)xmlElementAttributes;
- (id)initWithXMLElementDescription:(id)arg1 belongingToModel:(id)arg2;
@property(readonly) NSString *attributeTypeString;
- (void)setAttributeTypeIndex:(long long)arg1;
- (long long)attributeTypeIndex;
- (void)_createAttributeTypesArray;
- (id)addKeysToDictionary:(id)arg1;
- (id)initWithDictionary:(id)arg1;
- (void)generateErrorsAndWarningsWithCallback:(id)arg1 forDocumentAtURL:(id)arg2;
- (id)undoManager;
- (id)versionHash;
@property BOOL allowsExternalBinaryDataStorage; // @synthesize allowsExternalBinaryDataStorage;
- (void)setInspectedAttributeType:(long long)arg1;
- (id)nilDefaultAttributeTypes;
- (id)zeroDefaultAttributeTypes;
- (id)numericalMinMaxAttributeTypes;
- (long long)inspectedAttributeType;
@property(copy) id maxValueObject;
@property(copy) id minValueObject;
- (id)maxValueObjectNonNilValue;
- (id)minValueObjectNonNilValue;
- (id)defaultValueObjectNonNilValue;
@property id defaultValueObject;
- (id)defaultValueObjectForString:(id)arg1 withType:(long long)arg2;
- (void)cascadeChangesToLegacyAttribute:(id)arg1;
- (id)initWithLegacyAttribute:(id)arg1 belongingToEntity:(id)arg2 inModel:(id)arg3;
- (id)code_propertyTypePrimitiveParameter;
- (id)code_propertyTypePrimitive;
- (id)code_propertyTypePointer;
- (id)validateStringValue:(id)arg1 asType:(unsigned long long)arg2;
- (BOOL)willHangNaturalLanguageParser:(id)arg1;

@end

@interface CDMAttributeScriptingWrapper : IDEScriptingWrapper
{
}

- (void)setUserInfo:(id)arg1;
- (id)userInfo;
- (void)setTransient:(BOOL)arg1;
- (BOOL)transient;
- (void)setOptional:(BOOL)arg1;
- (BOOL)optional;
- (id)name;
- (void)setDefaultValue:(id)arg1;
- (id)defaultValue;
- (void)setAttributeType:(id)arg1;
- (id)attributeType;

@end

@interface CDMEntity : NSObject <CDMIdentification>
{
    NSString *name;
    NSString *representedClassName;
    NSMutableArray *attributes;
    NSMutableArray *fetchedProperties;
    NSMutableArray *relationships;
    NSMutableArray *allProperties;
    BOOL isAbstract;
    NSMutableDictionary *userInfoDictionary;
    NSString *elementID;
    NSString *versionHashModifier;
    NSMutableArray *descendants;
    CDMModel *model;
    NSNumber *uniqueID;
    CDMInheritanceRelationship *inheritanceRelationship;
    CDMInheritanceRelationship *oldInheritanceRelationship;
    NSMutableArray *compoundIndexes;
    BOOL syncable;
    BOOL excludeFromDataChangeAlert;
    NSString *syncName;
    NSString *dataClassName;
    NSString *parentRelationshipName;
}

+ (id)keyPathsForValuesAffectingDisplayedSyncName;
+ (id)dictionaryOfPropertyPLists:(id)arg1;
+ (id)keyPathsForValuesAffectingInspectedCompoundIndexes;
+ (id)keyPathsForValuesAffectingRelationshipsIncludingInheritance;
+ (id)keyPathsForValuesAffectingAllProperties;
+ (id)keyPathsForValuesAffectingInspectedSyncable;
+ (id)keyPathsForValuesAffectingSortedFetchedProperties;
+ (id)keyPathsForValuesAffectingSortedRelationships;
+ (id)keyPathsForValuesAffectingSortedAttributes;
@property(copy) NSString *parentRelationshipName; // @synthesize parentRelationshipName;
@property(copy) NSString *dataClassName; // @synthesize dataClassName;
@property(copy) NSString *syncName; // @synthesize syncName;
@property BOOL excludeFromDataChangeAlert; // @synthesize excludeFromDataChangeAlert;
@property BOOL syncable; // @synthesize syncable;
@property(copy) NSArray *compoundIndexes; // @synthesize compoundIndexes;
@property CDMInheritanceRelationship *oldInheritanceRelationship; // @synthesize oldInheritanceRelationship;
@property CDMInheritanceRelationship *inheritanceRelationship; // @synthesize inheritanceRelationship;
@property(copy) NSNumber *uniqueID; // @synthesize uniqueID;
@property CDMModel *model; // @synthesize model;
@property(copy) NSString *versionHashModifier; // @synthesize versionHashModifier;
@property(copy) NSString *elementID; // @synthesize elementID;
@property(copy) NSDictionary *userInfoDictionary; // @synthesize userInfoDictionary;
@property BOOL isAbstract; // @synthesize isAbstract;
@property(copy) NSArray *relationships; // @synthesize relationships;
@property(copy) NSArray *fetchedProperties; // @synthesize fetchedProperties;
@property(copy) NSArray *attributes; // @synthesize attributes;
@property(copy) NSString *representedClassName; // @synthesize representedClassName;
@property(copy) NSString *name; // @synthesize name;
- (id)stringRepresentation;
- (id)xmlElementDescription;
- (id)compoundIndexesXMLElementTree;
- (id)userInfoXMLElementTree;
- (id)initWithXMLElementDescription:(id)arg1 belongingToModel:(id)arg2;
- (id)xmlElementAttributes;
@property(readonly) NSString *defaultSyncName;
@property(readonly) NSString *displayedSyncName;
- (id)navigableItem_name;
- (void)generateErrorsAndWarningsWithCallback:(id)arg1 forDocumentAtURL:(id)arg2;
- (void)fillInStateWithDictionary:(id)arg1 entityNameMapTable:(id)arg2;
- (id)pastePropertiesWithDictionary:(id)arg1 entityNameMapTable:(id)arg2;
- (id)pasteFetchedPropertiesFromPlistArray:(id)arg1 entityNameMapTable:(id)arg2;
- (id)pasteFetchRequestsFromPlistArray:(id)arg1 entityNameMapTable:(id)arg2;
- (id)pasteRelationshipsFromPlistArray:(id)arg1 entityNameMapTable:(id)arg2;
- (id)pasteAttributesFromPlistArray:(id)arg1 entityNameMapTable:(id)arg2;
- (id)addKeysToDictionary:(id)arg1;
- (id)undoManager;
@property(readonly) NSData *versionHash;
- (void)cascadeChangesToLegacyEntity:(id)arg1;
- (id)initWithLegacyEntitysAttributes:(id)arg1 belongingToModel:(id)arg2;
- (void)updateSyncingSupport;
- (id)initWithName:(id)arg1 belongingToModel:(id)arg2;
- (void)commonInit;
- (id)descendants;
- (void)removeFetchedProperty:(id)arg1;
- (void)addFetchedProperty:(id)arg1;
- (void)removeRelationship:(id)arg1;
- (void)addRelationship:(id)arg1;
- (void)removeAttribute:(id)arg1;
- (void)addAttribute:(id)arg1;
- (void)removeDescendantEntity:(id)arg1;
- (void)addDescendantEntity:(id)arg1;
- (void)didChangeValueForKey:(id)arg1;
@property CDMEntity *inspectedParentEntity;
@property CDMEntity *parentEntity;
- (void)setInspectedCompoundIndexes:(id)arg1;
- (id)inspectedCompoundIndexes;
- (id)relationshipsIncludingInheritance;
@property(readonly) NSString *effectiveRepresentedClassName;
- (id)allPropertiesIncludingInheritance;
@property(readonly) NSArray *allProperties;
- (void)updateAllProperties;
- (id)targetedConfigurations;
- (id)targetedRelationships;
- (id)targetedFetchRequests;
- (id)inheritedPropertyForName:(id)arg1;
- (id)entityRelationshipForName:(id)arg1;
- (id)entityPropertyForName:(id)arg1;
- (id)possibleParentEntities;
- (id)owningConfigurations;
- (void)setInspectedSyncable:(BOOL)arg1;
- (BOOL)inspectedSyncable;
- (id)humanReadableNameForInspectorKeyPath:(id)arg1;
- (id)sortedFetchedProperties;
- (id)sortedRelationships;
- (id)sortedAttributes;
- (id)code_entityFileName;
- (id)proposedFileName;
- (BOOL)validateName:(id *)arg1 error:(id *)arg2;

@end

@interface CDMEntityScriptingWrapper : IDEScriptingWrapper
{
}

- (id)newScriptingObjectOfClass:(Class)arg1 forValueForKey:(id)arg2 withContentsValue:(id)arg3 properties:(id)arg4;
- (id)relationships;
- (id)fetchedProperties;
- (id)fetchRequests;
- (id)attributes;
- (void)setUserInfo:(id)arg1;
- (id)userInfo;
- (void)setParent:(id)arg1;
- (id)parent;
- (void)setObjectClass:(id)arg1;
- (id)objectClass;
- (id)name;
- (void)setAbstract:(BOOL)arg1;
- (BOOL)abstract;

@end

@interface CDMRelationship : CDMProperty
{
    CDMEntity *destinationEntity;
    unsigned long long minCount;
    unsigned long long maxCount;
    long long deletionRule;
    CDMRelationship *inverseRelationship;
    BOOL toMany;
    BOOL ordered;
}

+ (id)keyPathsForValuesAffectingInspectedToMany;
+ (id)keyPathsForValuesAffectingInspectedMaxCount;
+ (id)keyPathsForValuesAffectingInspectedMinCount;
+ (id)keyPathsForValuesAffectingInverseRelationship;
+ (id)keyPathsForValuesAffectingInspectedInverseRelationship;
+ (id)keyPathsForValuesAffectingInspectedDestinationEntity;
+ (id)keyPathsForValuesAffectingDestinationEntity;
+ (id)keyPathsForValuesAffectingPossibleInverseRelationships;
@property BOOL ordered; // @synthesize ordered;
@property BOOL toMany; // @synthesize toMany;
@property CDMRelationship *inverseRelationship; // @synthesize inverseRelationship;
@property long long deletionRule; // @synthesize deletionRule;
@property unsigned long long maxCount; // @synthesize maxCount;
@property unsigned long long minCount; // @synthesize minCount;
@property CDMEntity *destinationEntity; // @synthesize destinationEntity;
- (id)stringRepresentation;
- (id)xmlElementDescription;
- (id)xmlElementAttributes;
- (id)initWithXMLElementDescription:(id)arg1 belongingToModel:(id)arg2;
- (id)addKeysToDictionary:(id)arg1;
- (id)initWithDictionary:(id)arg1;
- (void)generateErrorsAndWarningsWithCallback:(id)arg1 forDocumentAtURL:(id)arg2;
- (id)undoManager;
- (id)filteredRelationshipsWithNoInverse;
- (id)versionHash;
@property BOOL inspectedToMany;
- (unsigned long long)inspectedMaxCountNonNilValue;
- (void)setInspectedMaxCount:(id)arg1;
- (id)inspectedMaxCount;
- (unsigned long long)inspectedMinCountNonNilValue;
- (void)setInspectedMinCount:(id)arg1;
- (id)inspectedMinCount;
@property CDMRelationship *inspectedInverseRelationship;
- (void)setDestinationEntity:(id)arg1 andInverseRelationship:(id)arg2;
@property CDMEntity *inspectedDestinationEntity;
- (void)setInspectedOptional:(BOOL)arg1;
- (id)possibleInverseRelationships;
- (void)cascadeChangesToLegacyRelationships:(id)arg1 givenModernToLegacyEntityMapping:(id)arg2;
- (id)initWithLegacyRelationship:(id)arg1 andEntityMapping:(id)arg2 belongingToEntity:(id)arg3 inModel:(id)arg4;
- (id)init;
- (id)code_unorderedAccessors;
- (id)code_orderedAccessors;
- (id)code_relationshipDestinationClass;
- (id)code_relationshipSetType;

@end

@interface CDMRelationshipScriptingWrapper : IDEScriptingWrapper
{
}

- (id)userInfo;
- (BOOL)ordered;
- (BOOL)transient;
- (BOOL)toMany;
- (BOOL)optional;
- (id)name;
- (long long)minimumCount;
- (long long)maximumCount;
- (id)inverseRelationship;
- (id)destinationEntity;

@end

@interface CDMFetchedProperty : CDMProperty <IDEInspectorMatching>
{
    CDMFetchRequest *fetchRequest;
}

- (id)stringRepresentation;
- (id)xmlElementDescription;
- (id)initWithXMLElementDescription:(id)arg1 belongingToModel:(id)arg2;
- (id)xmlElementFetchRequest;
- (id)addKeysToDictionary:(id)arg1;
- (id)initWithDictionary:(id)arg1;
- (void)cascadeChangesToLegacyFetchedProperty:(id)arg1 givenModernToLegacyEntityMapping:(id)arg2;
- (id)initWithLegacyFetchedProperty:(id)arg1 andEntityMapping:(id)arg2 belongingToEntity:(id)arg3 inModel:(id)arg4;
- (id)initForEntity:(id)arg1;
@property CDMFetchRequest *fetchRequest; // @synthesize fetchRequest;
- (id)applicableInspectorsForCategory:(id)arg1 suggestion:(id)arg2;

@end

@interface CDMFetchedPropertyScriptingWrapper : IDEScriptingWrapper
{
}

- (id)userInfo;
- (BOOL)transient;
- (id)predicate;
- (BOOL)optional;
- (id)name;
- (id)destination;

@end

@interface CDMFetchRequest : NSObject <IDEInspectorAccessibilitySupport, CDMIdentification>
{
    NSString *name;
    CDMEntity *entity;
    NSString *predicateString;
    unsigned long long fetchLimit;
    unsigned long long fetchOffset;
    unsigned long long fetchBatchSize;
    BOOL includeSubentities;
    BOOL includePropertyValues;
    BOOL includesPendingChanges;
    BOOL returnObjectsAsFaults;
    BOOL returnDistinctResults;
    CDMModel *model;
    long long resultType;
    NSNumber *uniqueID;
}

+ (id)fetchRequestFromPasteboardPlist:(id)arg1 model:(id)arg2;
@property(copy) NSNumber *uniqueID; // @synthesize uniqueID;
@property long long resultType; // @synthesize resultType;
@property CDMModel *model; // @synthesize model;
@property BOOL returnDistinctResults; // @synthesize returnDistinctResults;
@property BOOL returnObjectsAsFaults; // @synthesize returnObjectsAsFaults;
@property BOOL includesPendingChanges; // @synthesize includesPendingChanges;
@property BOOL includePropertyValues; // @synthesize includePropertyValues;
@property BOOL includeSubentities; // @synthesize includeSubentities;
@property unsigned long long fetchBatchSize; // @synthesize fetchBatchSize;
@property unsigned long long fetchOffset; // @synthesize fetchOffset;
@property unsigned long long fetchLimit; // @synthesize fetchLimit;
@property(copy) NSString *predicateString; // @synthesize predicateString;
@property CDMEntity *entity; // @synthesize entity;
@property(copy) NSString *name; // @synthesize name;
- (BOOL)validateName:(id *)arg1 error:(id *)arg2;
- (id)stringRepresentation;
- (id)xmlElementDescription;
- (id)xmlElementAttributes;
- (id)initWithXMLElementDescription:(id)arg1 belongingToModel:(id)arg2;
- (id)navigableItem_name;
- (id)addKeysToDictionary:(id)arg1;
- (id)initWithDictionary:(id)arg1;
- (id)undoManager;
- (void)cascadeChangesToLegacyFetchRequest:(id)arg1 givenModernToLegacyEntityMapping:(id)arg2;
- (id)initWithLegacyFetchRequest:(id)arg1 andEntityMapping:(id)arg2 belongingToModel:(id)arg3;
- (id)initWithName:(id)arg1 belongingToModel:(id)arg2 targettingEntity:(id)arg3;
- (void)commonInit;
- (id)humanReadableNameForInspectorKeyPath:(id)arg1;

@end

@interface CDMFetchRequestScriptingWrapper : IDEScriptingWrapper
{
}

- (id)name;
- (id)predicate;

@end

@interface CDMModel : NSObject <IDEInspectorAccessibilitySupport>
{
    NSString *name;
    NSMutableArray *entities;
    NSMutableArray *fetchRequests;
    NSMutableArray *configurations;
    NSString *modelVersionIdentifier;
    BOOL isLoading;
    IDEDataModelDocument *document;
    CDMConfiguration *defaultConfiguration;
    NSMutableArray *rootsOfEntityTree;
    NSMutableArray *topLevelObjects;
}

+ (id)arrayOfFetchRequestsPlistsFromFetchRequests:(id)arg1;
+ (id)arrayOfEntitiesPListsFromEntities:(id)arg1;
+ (id)keyPathsForValuesAffectingDisplayConfigurations;
+ (id)keyPathsForValuesAffectingRootsOfEntityTree;
@property(copy) NSArray *rootsOfEntityTree; // @synthesize rootsOfEntityTree;
@property CDMConfiguration *defaultConfiguration; // @synthesize defaultConfiguration;
@property IDEDataModelDocument *document; // @synthesize document;
@property(copy) NSString *name; // @synthesize name;
@property(copy) NSString *modelVersionIdentifier; // @synthesize modelVersionIdentifier;
@property(copy) NSArray *configurations; // @synthesize configurations;
@property(copy) NSArray *fetchRequests; // @synthesize fetchRequests;
@property(copy) NSArray *entities; // @synthesize entities;
- (id)stringRepresentation;
- (id)xmlDescription;
- (id)initWithXMLElementDescription:(id)arg1;
- (id)pasteEmptyEntitiesFromPList:(id)arg1;
- (void)fillInPastedEntitiesWithUpdatedPList:(id)arg1;
- (void)generateErrorsAndWarningsWithCallback:(id)arg1 forDocumentAtURL:(id)arg2;
- (id)entityForName:(id)arg1;
- (void)updateDefaultConfiguration;
- (id)undoManager;
- (id)descendantsOfEntity:(id)arg1;
- (id)displayConfigurations;
- (id)legacyRepresentation;
- (id)initWithLegacyModel:(id)arg1;
- (void)commonInit;
- (void)didChangeRootsOfEntityTree;
- (void)removeConfiguration:(id)arg1;
- (void)addConfiguration:(id)arg1;
- (void)removeFetchRequest:(id)arg1;
- (void)addFetchRequest:(id)arg1;
- (void)removeEntity:(id)arg1;
- (void)addEntity:(id)arg1;
@property(readonly) NSArray *topLevelObjects;
- (void)updateTopLevelObjects;
- (id)fetchRequestsForEntity:(id)arg1;
- (id)humanReadableNameForInspectorKeyPath:(id)arg1;

@end

@interface CDMConfiguration : NSObject <IDEInspectorAccessibilitySupport, CDMIdentification>
{
    NSString *name;
    NSMutableArray *entities;
    CDMModel *model;
    NSNumber *uniqueID;
}

+ (id)configurationFromPasteboradPlist:(id)arg1 model:(id)arg2;
@property(copy) NSNumber *uniqueID; // @synthesize uniqueID;
@property CDMModel *model; // @synthesize model;
- (id)stringRepresentation;
- (id)xmlElementDescription;
- (id)xmlElementAttributes;
- (id)initWithXMLElementDescription:(id)arg1 belongingToModel:(id)arg2;
- (id)navigableItem_name;
- (id)pasteboardPlist;
- (void)cascadeChangesToLegacyConfiguration:(id)arg1 givenModernToLegacyEntityMapping:(id)arg2;
- (id)initWithLegacyConfiguration:(id)arg1 andEntityMapping:(id)arg2 belongingToModel:(id)arg3;
- (id)initWithEntities:(id)arg1 andName:(id)arg2;
- (void)commonInit;
- (void)updateConfigurationWithEntities:(id)arg1;
- (void)addEntities:(id)arg1;
- (void)removeEntities:(id)arg1;
- (void)removeEntity:(id)arg1;
- (void)addEntity:(id)arg1;
@property(copy) NSArray *entities;
@property(copy) NSString *name;
- (id)humanReadableNameForInspectorKeyPath:(id)arg1;

@end

@interface CDMInheritanceRelationship : NSObject
{
    CDMEntity *parentEntity;
    NSNumber *uniqueID;
    CDMEntity *entity;
    CDMModel *model;
}

@property(copy) NSNumber *uniqueID; // @synthesize uniqueID;
@property CDMEntity *entity; // @synthesize entity;
@property CDMModel *model; // @synthesize model;
@property CDMEntity *parentEntity; // @synthesize parentEntity;
- (id)name;
- (id)init;

@end

@interface CDMModelManager : NSObject
{
}

+ (id)stringRepresentationOfModelObject:(id)arg1;

@end

@interface NSString (_CoreDataPlugin_Extensions)
- (long long)_xdcaseInsensitiveNumericCompare:(id)arg1;
@end

@interface NSManagedObject (_XDMappingModelUtilities)
- (void)_setValue:(id)arg1 forTransientKey:(id)arg2 persistentKey:(id)arg3;
- (id)_valueForTransientKey:(id)arg1 persistentKey:(id)arg2;
@end

@interface NSString (CDMFoundationAdditions)
+ (id)cdm_uniqueStringForString:(id)arg1 givenExistingStrings:(id)arg2;
@end

@interface NSBundle (IBFoundationBundleAdditions)
- (id)cdm_shortBundleVersion;
- (id)cdm_bundleVersion;
@end

