/*
 *     Generated by class-dump 3.3.3 (64 bit) (Debug version compiled Aug 11 2011 13:55:57).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#pragma mark Named Structures

struct CGPoint {
    double _field1;
    double _field2;
};

struct CGRect {
    struct CGPoint _field1;
    struct CGSize _field2;
};

struct CGSize {
    double _field1;
    double _field2;
};

struct NSObject {
    Class _field1;
};

struct _NSRange {
    unsigned long long _field1;
    unsigned long long _field2;
};

#pragma mark -

/*
 * File: /Developer/Library/Xcode/PrivatePlugIns/SharedPlugInUtilities.ideplugin/Contents/MacOS/SharedPlugInUtilities
 * UUID: 1B4C01A1-14CF-35BE-A9FD-D47CC6EB4897
 * Arch: Intel x86-64 (x86_64)
 *       Current version: 504.0.0, Compatibility version: 1.0.0
 *       Minimum Mac OS X version: 10.7.0
 *
 *       Objective-C Garbage Collection: Required
 */

@protocol NSControlTextEditingDelegate <NSObject>

@optional
- (id)control:(id)arg1 textView:(id)arg2 completions:(id)arg3 forPartialWordRange:(struct _NSRange)arg4 indexOfSelectedItem:(long long *)arg5;
- (BOOL)control:(id)arg1 textView:(id)arg2 doCommandBySelector:(SEL)arg3;
- (BOOL)control:(id)arg1 isValidObject:(id)arg2;
- (void)control:(id)arg1 didFailToValidatePartialString:(id)arg2 errorDescription:(id)arg3;
- (BOOL)control:(id)arg1 didFailToFormatString:(id)arg2 errorDescription:(id)arg3;
- (BOOL)control:(id)arg1 textShouldEndEditing:(id)arg2;
- (BOOL)control:(id)arg1 textShouldBeginEditing:(id)arg2;
@end

@protocol NSObject
- (id)description;
- (unsigned long long)retainCount;
- (id)autorelease;
- (oneway void)release;
- (id)retain;
- (BOOL)respondsToSelector:(SEL)arg1;
- (BOOL)conformsToProtocol:(id)arg1;
- (BOOL)isMemberOfClass:(Class)arg1;
- (BOOL)isKindOfClass:(Class)arg1;
- (BOOL)isProxy;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2 withObject:(id)arg3;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2;
- (id)performSelector:(SEL)arg1;
- (struct _NSZone *)zone;
- (id)self;
- (Class)class;
- (Class)superclass;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
@end

@protocol NSOutlineViewDataSource <NSObject>

@optional
- (id)outlineView:(id)arg1 namesOfPromisedFilesDroppedAtDestination:(id)arg2 forDraggedItems:(id)arg3;
- (BOOL)outlineView:(id)arg1 acceptDrop:(id)arg2 item:(id)arg3 childIndex:(long long)arg4;
- (unsigned long long)outlineView:(id)arg1 validateDrop:(id)arg2 proposedItem:(id)arg3 proposedChildIndex:(long long)arg4;
- (void)outlineView:(id)arg1 updateDraggingItemsForDrag:(id)arg2;
- (BOOL)outlineView:(id)arg1 writeItems:(id)arg2 toPasteboard:(id)arg3;
- (void)outlineView:(id)arg1 draggingSession:(id)arg2 endedAtPoint:(struct CGPoint)arg3 operation:(unsigned long long)arg4;
- (void)outlineView:(id)arg1 draggingSession:(id)arg2 willBeginAtPoint:(struct CGPoint)arg3 forItems:(id)arg4;
- (id)outlineView:(id)arg1 pasteboardWriterForItem:(id)arg2;
- (void)outlineView:(id)arg1 sortDescriptorsDidChange:(id)arg2;
- (id)outlineView:(id)arg1 persistentObjectForItem:(id)arg2;
- (id)outlineView:(id)arg1 itemForPersistentObject:(id)arg2;
- (void)outlineView:(id)arg1 setObjectValue:(id)arg2 forTableColumn:(id)arg3 byItem:(id)arg4;
- (id)outlineView:(id)arg1 objectValueForTableColumn:(id)arg2 byItem:(id)arg3;
- (BOOL)outlineView:(id)arg1 isItemExpandable:(id)arg2;
- (id)outlineView:(id)arg1 child:(long long)arg2 ofItem:(id)arg3;
- (long long)outlineView:(id)arg1 numberOfChildrenOfItem:(id)arg2;
@end

@protocol NSOutlineViewDelegate <NSControlTextEditingDelegate>

@optional
- (void)outlineViewItemDidCollapse:(id)arg1;
- (void)outlineViewItemWillCollapse:(id)arg1;
- (void)outlineViewItemDidExpand:(id)arg1;
- (void)outlineViewItemWillExpand:(id)arg1;
- (void)outlineViewSelectionIsChanging:(id)arg1;
- (void)outlineViewColumnDidResize:(id)arg1;
- (void)outlineViewColumnDidMove:(id)arg1;
- (void)outlineViewSelectionDidChange:(id)arg1;
- (BOOL)outlineView:(id)arg1 shouldShowOutlineCellForItem:(id)arg2;
- (BOOL)outlineView:(id)arg1 shouldReorderColumn:(long long)arg2 toColumn:(long long)arg3;
- (double)outlineView:(id)arg1 sizeToFitWidthOfColumn:(long long)arg2;
- (void)outlineView:(id)arg1 willDisplayOutlineCell:(id)arg2 forTableColumn:(id)arg3 item:(id)arg4;
- (BOOL)outlineView:(id)arg1 shouldCollapseItem:(id)arg2;
- (BOOL)outlineView:(id)arg1 shouldExpandItem:(id)arg2;
- (BOOL)outlineView:(id)arg1 isGroupItem:(id)arg2;
- (id)outlineView:(id)arg1 dataCellForTableColumn:(id)arg2 item:(id)arg3;
- (BOOL)outlineView:(id)arg1 shouldTrackCell:(id)arg2 forTableColumn:(id)arg3 item:(id)arg4;
- (BOOL)outlineView:(id)arg1 shouldShowCellExpansionForTableColumn:(id)arg2 item:(id)arg3;
- (BOOL)outlineView:(id)arg1 shouldTypeSelectForEvent:(id)arg2 withCurrentSearchString:(id)arg3;
- (id)outlineView:(id)arg1 nextTypeSelectMatchFromItem:(id)arg2 toItem:(id)arg3 forString:(id)arg4;
- (id)outlineView:(id)arg1 typeSelectStringForTableColumn:(id)arg2 item:(id)arg3;
- (double)outlineView:(id)arg1 heightOfRowByItem:(id)arg2;
- (id)outlineView:(id)arg1 toolTipForCell:(id)arg2 rect:(struct CGRect *)arg3 tableColumn:(id)arg4 item:(id)arg5 mouseLocation:(struct CGPoint)arg6;
- (void)outlineView:(id)arg1 didDragTableColumn:(id)arg2;
- (void)outlineView:(id)arg1 didClickTableColumn:(id)arg2;
- (void)outlineView:(id)arg1 mouseDownInHeaderOfTableColumn:(id)arg2;
- (BOOL)outlineView:(id)arg1 shouldSelectTableColumn:(id)arg2;
- (id)outlineView:(id)arg1 selectionIndexesForProposedSelection:(id)arg2;
- (BOOL)outlineView:(id)arg1 shouldSelectItem:(id)arg2;
- (BOOL)selectionShouldChangeInOutlineView:(id)arg1;
- (BOOL)outlineView:(id)arg1 shouldEditTableColumn:(id)arg2 item:(id)arg3;
- (void)outlineView:(id)arg1 willDisplayCell:(id)arg2 forTableColumn:(id)arg3 item:(id)arg4;
- (void)outlineView:(id)arg1 didRemoveRowView:(id)arg2 forRow:(long long)arg3;
- (void)outlineView:(id)arg1 didAddRowView:(id)arg2 forRow:(long long)arg3;
- (id)outlineView:(id)arg1 rowViewForItem:(id)arg2;
- (id)outlineView:(id)arg1 viewForTableColumn:(id)arg2 item:(id)arg3;
@end

@interface IDEConfigurableDataNode : NSObject
{
    IDEConfigurableDataNode *_parent;
    NSMutableArray *_children;
    id <XCEDataNodeAdapterP> _adapter;
    IDEConfigurableDataSource *_dataSource;
    id _data;
    NSImage *_cachedImage;
    double _cachedRowHeight;
    id _custom;
    struct {
        unsigned int invalidated:1;
        unsigned int childrenAreSorted:1;
        unsigned int cachedRowHeightDependsOnWidth:1;
        unsigned int willBeRemoved:1;
        unsigned int storedExpanded:1;
        unsigned int storedCollapsed:1;
        unsigned int storedSelected:1;
        unsigned int storedExpandedByDefault:1;
        unsigned int customFlag1:1;
        unsigned int customFlag2:1;
        unsigned int customFlag3:1;
        unsigned int adapterRespondsTo_invalidate:1;
        unsigned int adapterRespondsTo_representedFilename:1;
        unsigned int adapterRespondsTo_toolTipForTableColumn:1;
        unsigned int adapterRespondsTo_dataNodeConfigure:1;
        unsigned int adapterRespondsTo_objectValueForTableColumn:1;
        unsigned int adapterRespondsTo_setObjectValue:1;
        unsigned int adapterRespondsTo_dataNodeImage:1;
        unsigned int adapterRespondsTo_willDisplayCell:1;
        unsigned int adapterRespondsTo_dataCellForTableColumn:1;
        unsigned int adapterRespondsTo_shouldShowOutlineCell:1;
        unsigned int adapterRespondsTo_isGroupItem:1;
        unsigned int adapterRespondsTo_instantiateChildrenForDataNode:1;
        unsigned int adapterRespondsTo_filterChildData:1;
        unsigned int adapterRespondsTo_isDataNodeExpandable:1;
        unsigned int adapterRespondsTo_isDataNodeSelectable:1;
        unsigned int adapterRespondsTo_doubleClickInColumn:1;
        unsigned int adapterRespondsTo_shouldEditTableColumn:1;
        unsigned int adapterRespondsTo_handleMouseDown:1;
        unsigned int adapterRespondsTo_instantiateAddedChildWithData:1;
        unsigned int adapterRespondsTo_removeChild:1;
        unsigned int adapterRespondsTo_renameChild:1;
        unsigned int adapterRespondsTo_dropPaths:1;
        unsigned int adapterRespondsTo_removeDataNode:1;
        unsigned int adapterRespondsTo_refreshDataNode:1;
        unsigned int adapterRespondsTo_compareDataNode:1;
        unsigned int adapterRespondsTo_editorViewControllerForDataNode:1;
        unsigned int adapterRespondsTo_inspectorViewControllersForDataNode:1;
        unsigned int adapterRespondsTo_persistentObjectComponent:1;
        unsigned int adapterRespondsTo_matchesPersistentObjectComponent:1;
        unsigned int adapterRespondsTo_heightOfRowForDataNode:1;
        unsigned int adapterRespondsTo_canAcceptDroppedItem:1;
        unsigned int adapterRespondsTo_canAcceptDroppedItems:1;
        unsigned int adapterRespondsTo_acceptDroppedItems:1;
        unsigned int adapterRespondsTo_isDataNodeDragDeletable:1;
        unsigned int adapterRespondsTo_shouldSortChildrenOfNode:1;
        unsigned int adapterRespondsTo_frameOfOutlineCellAtRow:1;
        unsigned int _reserved:18;
    } _flags;
}

+ (id)minimumNodeCoverFromNodesInArray:(id)arg1;
+ (id)dataNodeWithData:(id)arg1 adapter:(id)arg2 dataSource:(id)arg3;
+ (id)dataNodeWithData:(id)arg1 adapter:(id)arg2;
@property(retain, nonatomic) id custom; // @synthesize custom=_custom;
@property(nonatomic) double cachedRowHeight; // @synthesize cachedRowHeight=_cachedRowHeight;
@property(retain, nonatomic) NSImage *cachedImage; // @synthesize cachedImage=_cachedImage;
- (void)consistencyCheck;
- (void)scrollToVisible;
- (void)selectInOutlineView;
- (void)setNeedsDisplay;
- (id)previousNodeInTreeLoadIfNecessary:(BOOL)arg1 wrap:(BOOL)arg2;
- (id)lastChildRecursivelyOrSelfLoadIfNecessary:(BOOL)arg1;
- (id)nextNodeInTreeLoadIfNecessary:(BOOL)arg1 wrap:(BOOL)arg2;
- (id)previousSibling;
- (id)nextSibling;
- (BOOL)isExpandedByDefault;
- (void)expandSelfAndParentsAndChildren;
- (void)expandOutlineAsNecessaryForVisibility;
- (void)expandSelfAndParents;
- (BOOL)handleReturnKey:(id)arg1 forOutlineView:(id)arg2 changeFocus:(BOOL)arg3;
- (BOOL)handleMouseDown:(id)arg1 forOutlineView:(id)arg2 inRow:(long long)arg3;
@property(readonly, nonatomic) id context; // @dynamic context;
@property(readonly, nonatomic) NSOutlineView *outlineView; // @dynamic outlineView;
- (void)removeSelf;
- (BOOL)matchesPersistentObjectComponent:(id)arg1;
- (id)persistentObjectComponent;
- (BOOL)dropPaths:(id)arg1 atIndex:(long long)arg2;
- (void)dropItems:(id)arg1 atIndex:(long long)arg2;
- (BOOL)canDropItems:(id)arg1 atIndex:(long long)arg2;
- (void)clearExpandedByDefault;
- (id)dataArrayForConsistencyCheck;
- (void)refreshNodeFor:(id)arg1;
- (void)replaceNodeFor:(id)arg1 withNodeFor:(id)arg2 at:(id)arg3;
- (void)renamedNodeFor:(id)arg1 within:(id)arg2;
- (void)removeNodeFor:(id)arg1 from:(id)arg2;
- (id)_findSubNodeWithData:(id)arg1;
- (BOOL)considerDataEqual:(id)arg1;
- (void)addNodeFor:(id)arg1 to:(id)arg2;
- (long long)compareInverse:(id)arg1;
- (long long)compare:(id)arg1;
- (BOOL)outlineViewIsGroupItem:(id)arg1;
- (struct CGRect)frameOfOutlineCellAtRow:(long long)arg1 defaultFrame:(struct CGRect)arg2;
- (void)noteHeightOfRowChanged;
- (void)voidWidthDependentCachedRowHeights;
- (double)rowHeight;
- (id)toolTipForTableColumn:(id)arg1 forCell:(id)arg2 rect:(struct CGRect *)arg3 mouseLocation:(struct CGPoint)arg4;
- (id)toolTipForTableColumn:(id)arg1;
- (BOOL)outlineViewShouldShowOutlineCell:(id)arg1;
- (id)outlineView:(id)arg1 dataCellForTableColumn:(id)arg2;
- (void)outlineView:(id)arg1 willDisplayCell:(id)arg2 forTableColumn:(id)arg3;
- (void)setObjectValue:(id)arg1 forTableColumn:(id)arg2;
- (id)objectValueForTableColumn:(id)arg1;
- (id)description;
- (void)recursiveSortChildren;
- (void)sortImmediateChildren;
- (BOOL)isDescendantOfNodeInArray:(id)arg1;
- (BOOL)isDescendantOfNode:(id)arg1;
- (id)inspectorViewControllersForEditor:(id)arg1;
- (id)editorViewController;
- (BOOL)shouldEditTableColumn:(id)arg1;
- (BOOL)doubleClickInColumn:(id)arg1;
- (id)representedFilename;
- (BOOL)isDragDeletable;
- (BOOL)isSelectable;
- (BOOL)isExpanded;
- (BOOL)isExpandable;
- (id)childAtIndex:(long long)arg1;
- (id)lastChild;
- (id)firstChild;
- (long long)numberOfChildren;
- (void)discardPreloadedChildren;
- (id)addChildForDataObject:(id)arg1 withAdapter:(struct NSObject *)arg2;
- (void)addChildrenForDataObjects:(id)arg1 withCommonAdapter:(struct NSObject *)arg2;
@property(copy, nonatomic) NSArray *children;
- (void)removeChildrenAtIndexes:(id)arg1;
- (void)insertChildren:(id)arg1 atIndexes:(id)arg2;
- (void)removeObjectFromChildrenAtIndex:(unsigned long long)arg1;
- (void)insertObject:(id)arg1 inChildrenAtIndex:(unsigned long long)arg2;
- (id)objectInChildrenAtIndex:(unsigned long long)arg1;
- (unsigned long long)countOfChildren;
- (id)mutableChildren;
- (BOOL)childrenAreLoaded;
- (long long)indexOfChildIdenticalTo:(id)arg1;
- (long long)indexOfChild:(id)arg1;
- (void)removeTree;
- (void)unlinkTree;
- (void)linkTreeToParent:(id)arg1 dataSource:(id)arg2;
- (void)removeFromParent;
- (void)removeChild:(id)arg1;
- (void)_removeChildrenIdenticalTo:(id)arg1;
- (void)addChildren:(id)arg1;
- (void)insertChildren:(id)arg1 atIndex:(long long)arg2;
- (void)insertChild:(id)arg1 atIndex:(long long)arg2;
- (void)addChild:(id)arg1;
- (id)_instantiatedChildren;
@property(nonatomic) BOOL willBeRemoved; // @dynamic willBeRemoved;
@property(nonatomic) BOOL customFlag3; // @dynamic customFlag3;
@property(nonatomic) BOOL customFlag2; // @dynamic customFlag2;
@property(nonatomic) BOOL customFlag1; // @dynamic customFlag1;
@property(nonatomic) BOOL storedExpandedByDefault; // @dynamic storedExpandedByDefault;
@property(nonatomic) BOOL cachedRowHeightDependsOnWidth; // @dynamic cachedRowHeightDependsOnWidth;
- (id)image;
@property(retain, nonatomic) id <XCEDataNodeAdapterP> adapter; // @synthesize adapter=_adapter;
- (void)clear;
- (void)invalidate;
@property(nonatomic) IDEConfigurableDataSource *dataSource; // @dynamic dataSource;
@property(nonatomic) IDEConfigurableDataNode *parent;
@property(retain, nonatomic) id data;
- (void)dealloc;
- (id)initWithData:(id)arg1 parent:(id)arg2 children:(id)arg3 adapter:(id)arg4 dataSource:(id)arg5;
- (id)initWithData:(id)arg1 parent:(id)arg2 children:(id)arg3 adapter:(id)arg4;

@end

@interface IDEConfigurableDataSource : NSObject <NSOutlineViewDataSource, NSOutlineViewDelegate>
{
    NSMutableArray *_roots;
    NSMutableArray *_displayedRoots;
    NSArray *_draggedNodes;
    NSTableColumn *_imageColumn;
    id <XCEDataRootAdapterP> _rootAdapter;
    NSArray *_draggedRootNodes;
    NSOutlineView *_outlineView;
    id _context;
    NSMapTable *_nodesForData;
    long long _batchUpdateLevel;
    struct {
        unsigned int _reserved:10;
        _Bool cleared;
        unsigned int _draggedNodesAreDeletable:1;
        unsigned int _draggedOutsideOutlineView:1;
        unsigned int _adapterRespondsTo_addRootPaths:1;
        unsigned int _adapterRespondsTo_moveDataNodes:1;
        unsigned int _adapterRespondsTo_removeRootDataNode:1;
        unsigned int _adapterRespondsTo_doubleClickDataNode:1;
        unsigned int _adapterRespondsTo_selectDataNode:1;
        unsigned int _adapterRespondsTo_textDidEndEditing:1;
        unsigned int _adapterRespondsTo_updateAndSaveRoots:1;
        unsigned int _adapterRespondsTo_askToDeleteRootNodes:1;
        unsigned int _adapterRespondsTo_contextMenuForSelectedNodes:1;
        unsigned int _adapterRespondsTo_pasteboardFilenamesForNodes:1;
        unsigned int _adapterRespondsTo_writeItemsToPasteboard:1;
        unsigned int _adapterRespondsTo_createItemsFromPasteboard:1;
        unsigned int _adapterRespondsTo_acceptDrop:1;
        unsigned int _adapterRespondsTo_canAcceptDroppedItem:1;
        unsigned int _adapterRespondsTo_validateDrop:1;
        unsigned int _adapterRespondsTo_acceptDroppedItems:1;
        unsigned int _adapterRespondsTo_didFailToFormatString:1;
        unsigned int _adapterRespondsTo_sortDescriptorsDidChange:1;
        unsigned int _adapterRespondsTo_filterDisplayedRootNode:1;
    } _flags;
}

+ (void)configureScrollView:(id)arg1 withOutlineView:(id)arg2;
+ (id)selectedNodeIfExactlyOneForOutlineView:(id)arg1;
+ (id)arrayOfSelectedNodesForOutlineView:(id)arg1;
+ (id)dataSourceWithRootAdapter:(id)arg1;
@property(nonatomic) NSOutlineView *outlineView; // @synthesize outlineView=_outlineView;
@property(copy) NSArray *draggedNodes; // @synthesize draggedNodes=_draggedNodes;
@property(nonatomic) id context; // @synthesize context=_context;
@property(retain, nonatomic) NSTableColumn *imageColumn; // @synthesize imageColumn=_imageColumn;
@property(retain, nonatomic) NSMutableArray *roots; // @synthesize roots=_roots;
- (void)configureDragAndDropForOutlineView:(id)arg1;
- (void)configureOutlineView:(id)arg1;
- (void)configureOutlineView:(id)arg1 withColumnTitled:(id)arg2 roots:(id)arg3 rootAdapter:(id)arg4 useImages:(BOOL)arg5 sourceList:(BOOL)arg6;
- (void)endBatchUpdates;
- (void)beginBatchUpdates;
- (BOOL)handleMouseDown:(id)arg1 forOutlineView:(id)arg2;
- (void)updateVisibleRowHeightsPlusExtension:(unsigned long long)arg1;
- (struct _NSRange)visibleRowRangePlusExtension:(unsigned long long)arg1;
- (void)setNeedsDisplayForRow:(long long)arg1;
- (id)nodeOrNodeSetForData:(id)arg1 withinNode:(id)arg2;
- (void)_removeCachesForNodeAndItsData:(id)arg1;
- (void)_addCachesForNodeAndItsDataRecursively:(id)arg1;
- (void)_addCachesForNodeAndItsData:(id)arg1;
- (id)selectedData;
- (id)exactlyOneSelectedNode;
- (id)selectedNodes;
- (void)consistencyCheck;
- (id)findNodeFor:(id)arg1 recursivelyStartingWith:(id)arg2;
- (id)findNodeFor:(id)arg1 withinParent:(id)arg2;
- (void)outlineView:(id)arg1 draggedImage:(id)arg2 endedAt:(struct CGPoint)arg3 operation:(unsigned long long)arg4;
- (void)outlineView:(id)arg1 draggedImage:(id)arg2 movedTo:(struct CGPoint)arg3;
- (void)outlineView:(id)arg1 draggedImage:(id)arg2 beganAt:(struct CGPoint)arg3;
- (void)_showDisappearanceAnimationEffectForDragAtPoint:(struct CGPoint)arg1;
- (void)_disappearanceAnimationEffectDidEnd:(void *)arg1;
- (void)_setDragSlideBack:(BOOL)arg1;
- (void)doubleClickAction:(id)arg1;
- (void)outlineView:(id)arg1 completeDeletionOfSelectedRowsByUser:(BOOL)arg2;
- (void)outlineView:(id)arg1 deleteSelectedRowsByUser:(BOOL)arg2;
- (unsigned long long)outlineView:(id)arg1 validateDrop:(id)arg2 proposedItem:(id)arg3 proposedChildIndex:(long long)arg4;
- (BOOL)outlineView:(id)arg1 acceptDrop:(id)arg2 item:(id)arg3 childIndex:(long long)arg4;
- (BOOL)outlineView:(id)arg1 createItemsFromPasteboard:(id)arg2;
- (void)outlineView:(id)arg1 deleteItems:(id)arg2;
- (id)outlineView:(id)arg1 menuForTableColumn:(id)arg2 row:(long long)arg3;
- (id)contextMenuForOutlineView:(id)arg1;
- (BOOL)handleReturnKey:(id)arg1 forOutlineView:(id)arg2 changeFocus:(BOOL)arg3;
- (BOOL)outlineView:(id)arg1 writeItems:(id)arg2 toPasteboard:(id)arg3;
- (BOOL)organizerOutlineView:(id)arg1 acceptDrop:(id)arg2 item:(id)arg3 childIndex:(long long)arg4;
- (unsigned long long)organizerOutlineView:(id)arg1 validateDrop:(id)arg2 proposedItem:(id)arg3 proposedChildIndex:(long long)arg4;
- (BOOL)organizerOutlineView:(id)arg1 writeItems:(id)arg2 toPasteboard:(id)arg3;
- (void)outlineView:(id)arg1 sortDescriptorsDidChange:(id)arg2;
- (void)outlineViewSelectionDidChange:(id)arg1;
- (BOOL)control:(id)arg1 didFailToFormatString:(id)arg2 errorDescription:(id)arg3;
- (void)controlTextDidEndEditing:(id)arg1;
- (id)arrayOfNonDefaultCollapsedPersistentObjects;
- (id)arrayOfNonDefaultExpandedPersistentObjects;
- (void)expandNodesToDefaultState;
- (void)expandArrayOfPersistentObjects:(id)arg1 forOutlineView:(id)arg2;
- (id)arrayOfExpandedPersistentObjectsForOutlineView:(id)arg1;
- (void)collapseArrayOfPersistentObjects:(id)arg1 forOutlineView:(id)arg2;
- (id)arrayOfCollapsedPersistentObjectsForOutlineView:(id)arg1;
- (void)selectArrayOfPersistentObjects:(id)arg1 forOutlineView:(id)arg2;
- (id)arrayOfSelectedPersistentObjectsForOutlineView:(id)arg1;
- (void)enumerateDataNodesForPersistentObjects:(id)arg1 loadIfNecessary:(BOOL)arg2 usingBlock:(id)arg3;
- (id)arrayOfPersistentObjectsFromDataNodesPassingTest:(id)arg1;
- (void)_addPersistentObjectForNode:(id)arg1 toArray:(id)arg2 ifPassingTest:(id)arg3;
- (id)outlineView:(id)arg1 persistentObjectForItem:(id)arg2;
- (id)outlineView:(id)arg1 itemForPersistentObject:(id)arg2;
- (id)outlineView:(id)arg1 itemForPersistentObject:(id)arg2 loadIfNecessary:(BOOL)arg3;
- (id)dataNodeForPersistentObject:(id)arg1 loadIfNecessary:(BOOL)arg2;
- (struct CGRect)frameOfOutlineCellAtRow:(long long)arg1 defaultFrame:(struct CGRect)arg2;
- (BOOL)outlineView:(id)arg1 isGroupItem:(id)arg2;
- (BOOL)outlineView:(id)arg1 shouldShowOutlineCellForItem:(id)arg2;
- (id)outlineView:(id)arg1 dataCellForTableColumn:(id)arg2 item:(id)arg3;
- (void)outlineView:(id)arg1 willDisplayCell:(id)arg2 forTableColumn:(id)arg3 item:(id)arg4;
- (BOOL)outlineView:(id)arg1 shouldShowCellExpansionForTableColumn:(id)arg2 item:(id)arg3;
- (id)outlineView:(id)arg1 toolTipForCell:(id)arg2 rect:(struct CGRect *)arg3 tableColumn:(id)arg4 item:(id)arg5 mouseLocation:(struct CGPoint)arg6;
- (BOOL)outlineView:(id)arg1 shouldSelectItem:(id)arg2;
- (void)outlineView:(id)arg1 setObjectValue:(id)arg2 forTableColumn:(id)arg3 byItem:(id)arg4;
- (BOOL)outlineView:(id)arg1 shouldEditTableColumn:(id)arg2 item:(id)arg3;
- (void)voidWidthDependentCachedRowHeights;
- (double)outlineView:(id)arg1 heightOfRowByItem:(id)arg2;
- (id)outlineView:(id)arg1 objectValueForTableColumn:(id)arg2 byItem:(id)arg3;
- (BOOL)outlineView:(id)arg1 isItemExpandable:(id)arg2;
- (id)outlineView:(id)arg1 child:(long long)arg2 ofItem:(id)arg3;
- (long long)outlineView:(id)arg1 numberOfChildrenOfItem:(id)arg2;
- (id)_childrenOfItem:(id)arg1;
- (id)addRootForDataObject:(id)arg1 withAdapter:(struct NSObject *)arg2;
- (void)removeRoot:(id)arg1;
- (void)addRootsForDataObjects:(id)arg1 withCommonAdapter:(struct NSObject *)arg2;
@property(retain, nonatomic) id <XCEDataRootAdapterP> rootAdapter;
- (void)reloadDataAndDisplayedNodes;
- (id)displayedRoots;
- (void)voidDisplayedRoots;
- (void)dealloc;
- (BOOL)isCleared;
- (void)clear;
- (id)init;

@end

@interface IDE_StorageForCGFloat : NSObject
{
    double cgFloat;
}

@end

@interface IDEConfigurableImageAndTextCell : NSTextFieldCell
{
    NSImage *_image;
    double _verticalOffsetForText;
    double _verticalOffsetForImage;
    double _leftMargin;
    double _imageTextGap;
    double _fontHeight;
    BOOL _useSourceListStyle;
    BOOL _currentlyEditingLocalScope;
    BOOL _useWizardTheme;
    BOOL _useBasicDropShadow;
}

+ (double)rowHeightForFont:(id)arg1 sourceList:(BOOL)arg2;
+ (double)rowHeightForFontHeight:(double)arg1 sourceList:(BOOL)arg2;
+ (double)fontHeightForFont:(id)arg1;
@property BOOL useBasicDropShadow; // @synthesize useBasicDropShadow=_useBasicDropShadow;
@property BOOL useWizardTheme; // @synthesize useWizardTheme=_useWizardTheme;
@property BOOL useSourceListStyle; // @synthesize useSourceListStyle=_useSourceListStyle;
@property double imageTextGap; // @synthesize imageTextGap=_imageTextGap;
@property double leftMargin; // @synthesize leftMargin=_leftMargin;
@property double verticalOffsetForImage; // @synthesize verticalOffsetForImage=_verticalOffsetForImage;
@property double verticalOffsetForText; // @synthesize verticalOffsetForText=_verticalOffsetForText;
- (unsigned long long)hitTestForEvent:(id)arg1 inRect:(struct CGRect)arg2 ofView:(id)arg3;
- (struct CGSize)cellSize;
- (void)drawWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (id)basicDropShadow;
- (void)drawWizardThemeBackgroundWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (void)drawSourceListBackground:(struct CGRect)arg1;
- (void)_setCurrentlyEditing:(BOOL)arg1;
- (void)endEditing:(id)arg1;
- (void)selectWithFrame:(struct CGRect)arg1 inView:(id)arg2 editor:(id)arg3 delegate:(id)arg4 start:(long long)arg5 length:(long long)arg6;
- (void)editWithFrame:(struct CGRect)arg1 inView:(id)arg2 editor:(id)arg3 delegate:(id)arg4 event:(id)arg5;
- (id)setUpFieldEditorAttributes:(id)arg1;
- (struct CGRect)titleRectForBounds:(struct CGRect)arg1 inView:(id)arg2;
- (struct CGRect)titleRectForBounds:(struct CGRect)arg1;
- (struct CGRect)imageRectForBounds:(struct CGRect)arg1;
- (double)_preTextAreaWidth;
@property(retain, nonatomic) NSImage *image; // @synthesize image=_image;
- (void)setFont:(id)arg1;
- (void)_internalEndEditing;
- (void)_internalBeginEditing;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (id)initTextCell:(id)arg1;
- (id)init;
- (void)initializeValues;
- (void)configureWithFont:(id)arg1 sourceList:(BOOL)arg2;
- (double)rowHeightForCurrentFont;
- (double)rowHeightForFont:(id)arg1;
- (void)notifyEndEditing;
- (void)notifyBeginEditing;

@end

@interface NSMutableArray (IDEConfigurableDataNodeArrayExtensions)
- (void)IDE_insertObjects:(id)arg1 inArraySortedUsingComparator:(id)arg2;
- (void)IDE_insertObject:(id)arg1 inArraySortedUsingComparator:(id)arg2;
- (void)IDE_insertObjects:(id)arg1 inArraySortedUsingSelector:(SEL)arg2;
- (void)IDE_insertObject:(id)arg1 inArraySortedUsingSelector:(SEL)arg2;
@end

